- docs/src/pages/components/cdk-components/button/Tokens.jsx
- docs/src/pages/components/cdk-components/button/api.jsx
- docs/src/pages/components/cdk-components/checkbox/Tokens.jsx
- docs/src/pages/components/common/SampleComponent.jsx
- lib/src/button/Button.jsx
- lib/src/common/variables.js
Added color sample component and added it to the button and checkbox + some button improvements
> Adding color sample component + small fixes

- app/src/pages/Select.jsx
- docs/src/pages/components/cdk-components/select/Select.jsx
- docs/src/pages/components/cdk-components/select/Tokens.jsx
- docs/src/pages/components/cdk-components/select/api.jsx
- docs/src/pages/components/common/SampleComponent.jsx
- lib/src/common/variables.js
- lib/src/select/Select.jsx
Added support for checkbox theming in the select when multiple and a small fix for the color sample component
> adding theming tokens to select

- docs/src/pages/components/Components.jsx
> Mparrilla components page

- docs/src/pages/components/cdk-components/alert/Alert.jsx
- docs/src/pages/components/cdk-components/autocomplete/Autocomplete.jsx
- docs/src/pages/components/cdk-components/box/Box.jsx
- docs/src/pages/components/cdk-components/card/Card.jsx
- docs/src/pages/components/cdk-components/dialog/Dialog.jsx
- docs/src/pages/components/cdk-components/heading/Heading.jsx
- docs/src/pages/components/cdk-components/link/Link.jsx
- docs/src/pages/components/cdk-components/resultsetTable/resultsetTable.jsx
- docs/src/pages/components/cdk-components/tabbed-sections/TabbedSections.jsx
- docs/src/pages/components/cdk-components/tag/Tag.jsx
- docs/src/pages/components/cdk-components/textarea/Textarea.jsx
- docs/src/pages/components/cdk-components/upload/Upload.jsx
Added theming tab to all components.
> Default theming tab

- docs/src/pages/components/cdk-components/footer/Tokens.jsx
- docs/src/pages/components/cdk-components/footer/api.jsx
- docs/src/pages/components/cdk-components/header/Tokens.jsx
- docs/src/pages/components/cdk-components/header/api.jsx
- lib/src/common/variables.js
- lib/src/footer/Footer.jsx
- lib/src/footer/readme.md
- lib/src/header/Header.jsx
- lib/src/header/readme.md
Thematizable logos in header and footer.
> Mparrilla logos

- docs/src/pages/overview/Overview.jsx
Correct link to Components list.
> Fix url to components list

- lib/src/button/Button.jsx
> Fixed secondary button

- docs/src/pages/components/cdk-components/toggleGroup/examples/controlledToggleGroup.js
- lib/src/toggle-group/ToggleGroup.jsx
Now the controlled toggle group example is simpler. Removed some logs from the component.
> Mparrilla togglegroup fixes

- app/src/pages/Tag.jsx
- docs/src/pages/components/cdk-components/tag/api.jsx
- lib/src/tag/Tag.jsx
> Tag new window and button render

- app/src/pages/Link.jsx
- docs/src/pages/components/cdk-components/link/Link.jsx
- docs/src/pages/components/cdk-components/link/api.jsx
- docs/src/pages/components/cdk-components/link/examples/iconLink.js
- lib/src/link/Link.jsx
- lib/test/Link.test.js
New onClick prop and render as button when received.
> Link onClick prop

- docs/src/pages/components/Components.jsx
- docs/src/pages/components/cdk-components/tabbed-sections/api.jsx
- lib/src/header/Header.jsx
- lib/src/select/Select.jsx
- lib/src/sidenav/Sidenav.jsx
- lib/src/table/Table.jsx
- lib/src/tabs-for-sections/TabsForSections.jsx
- lib/src/toggle-group/ToggleGroup.jsx
Fixing different warnings and updated props of TabbedSection component.
> Warnings fixes

- app/src/pages/Slider.jsx
- docs/src/pages/components/cdk-components/slider/api.jsx
- docs/src/pages/components/cdk-components/slider/examples/uncontrolled.js
- lib/src/slider/Slider.jsx
- lib/test/Slider.test.js
Related issue: https://github.com/dxc-technology/halstack-style-guide/issues/8
> New prop labelFormatCallback in slider

- docs/package.json
- docs/src/common/Header.jsx
- docs/src/common/portal.json
- scripts/release-docs.js
Added selection of version in the site header.
> Version selection in site

- docs/src/pages/overview/Overview.jsx
Sample code formatted and use of Link component in Overview page.
> Fixes in site Overview page

- app/src/pages/Sidenav.jsx
- docs/src/pages/components/cdk-components/sidenav/Sidenav.jsx
- docs/src/pages/components/cdk-components/sidenav/examples/compound.jsx
- docs/src/pages/components/cdk-components/sidenav/linkapi.jsx
- lib/src/sidenav/Sidenav.jsx
- lib/test/Sidenav.test.js
Sidenav component now supports three customized components: Title, Subtitle and Link.
> Sidenav with components

- lib/src/layout/ApplicationLayout.jsx
Fixed issue when sidenav is closed in responsive and resized to desktop.
> Sidenav visible when resized

- app/src/pages/Button.jsx
- docs/src/pages/components/cdk-components/button/api.jsx
- docs/src/pages/components/cdk-components/button/examples/withIcon.js
- lib/src/button/Button.jsx
New prop icon in button component.
> Icon in button component

- app/src/pages/Chip.jsx
- docs/src/pages/components/cdk-components/chip/api.jsx
- docs/src/pages/components/cdk-components/chip/examples/suffixPrefix.js
- lib/src/chip/Chip.jsx
New props in chip component: prefixIcon and suffixIcon.
> Prefix and suffix icon prop in chip component

- app/src/pages/Footer.jsx
- docs/src/pages/components/cdk-components/footer/api.jsx
- docs/src/pages/components/cdk-components/footer/examples/children.js
- docs/src/pages/components/cdk-components/footer/examples/default.js
- lib/src/footer/Footer.jsx
New prop logo in footer and logo in footer socialLinks.
> Logo prop in footer component

- app/src/pages/InputText.jsx
- docs/src/pages/components/cdk-components/input/api.jsx
- docs/src/pages/components/cdk-components/input/examples/lebeledInput.js
- lib/src/input-text/InputText.jsx
New props in input text component: prefixIcon and suffixIcon.
> Prefix and suffix icon prop in input text component

- app/src/pages/Link.jsx
- docs/src/pages/components/cdk-components/link/api.jsx
- docs/src/pages/components/cdk-components/link/examples/iconLink.js
- lib/src/link/Link.jsx
New prop icon in link component.
> Icon prop in link component

- app/src/pages/Select.jsx
- docs/src/pages/components/cdk-components/select/api.jsx
- docs/src/pages/components/cdk-components/select/examples/sizedSelect.js
- docs/src/pages/components/cdk-components/select/examples/withIcons.js
- lib/src/select/Select.jsx
> Icon prop in select component

- app/src/pages/Tag.jsx
- docs/src/pages/components/cdk-components/tag/api.jsx
- docs/src/pages/components/cdk-components/tag/examples/actionExample.js
- docs/src/pages/components/cdk-components/tag/examples/basicExample.js
- docs/src/pages/components/cdk-components/tag/examples/linkExample.js
- docs/src/pages/components/cdk-components/tag/examples/sized.js
- lib/src/tag/Tag.jsx
New prop icon in tag component.
> Icon prop in tag component

- app/src/pages/ToggleGroup.jsx
- docs/src/pages/components/cdk-components/toggleGroup/api.jsx
- docs/src/pages/components/cdk-components/toggleGroup/examples/withIcons.js
- lib/src/toggle-group/ToggleGroup.jsx
New prop icon in toggle group component.
> Icon prop in toggle group component

- app/src/pages/Wizard.jsx
- docs/src/pages/components/cdk-components/wizard/api.jsx
- docs/src/pages/components/cdk-components/wizard/examples/uncontrolledWizard.js
- lib/src/wizard/Wizard.jsx
New icon prop in wizard component.
> Icon prop in wizard component

- app/src/pages/Paginator.jsx
- app/src/pages/ResultsetTable.jsx
- docs/src/pages/components/cdk-components/paginator/Paginator.jsx
- docs/src/pages/components/cdk-components/paginator/api.jsx
- docs/src/pages/components/cdk-components/paginator/examples/paginatorItemsPerPage.js
- docs/src/pages/components/cdk-components/resultsetTable/api.jsx
- docs/src/pages/components/cdk-components/resultsetTable/examples/defaultResultseltTable.js
- lib/src/paginator/Paginator.jsx
- lib/src/resultsetTable/ResultsetTable.jsx
- lib/test/Paginator.test.js
- lib/test/ResultsetTable.test.js
Added new props for items per page: itemsPerPageOptions, itemsPerPageFunction.
> Paginator items per page new props

- app/src/pages/Paginator.jsx
- app/src/pages/ResultsetTable.jsx
- docs/src/pages/components/cdk-components/paginator/api.jsx
- docs/src/pages/components/cdk-components/paginator/examples/paginatorItemsPerPage.js
- docs/src/pages/components/cdk-components/resultsetTable/api.jsx
- docs/src/pages/components/cdk-components/resultsetTable/examples/defaultResultseltTable.js
- lib/src/paginator/Paginator.jsx
- lib/test/Paginator.test.js
- lib/test/ResultsetTable.test.js
Paginator itemsPerPageOptions prop is now an array of numbers.
> Paginator itemsPerPageOptions

- app/src/pages/Link.jsx
- lib/src/link/Link.jsx
- lib/test/Link.test.js
Disabled link is working as expected: if href is passed we ignore it, if onClick is passed we don't call it.
> Disabled link fix

- docs/src/pages/components/cdk-components/accordion-group/examples/controlledAccordionGroup.js
- lib/src/accordion-group/AccordionGroup.jsx
- lib/test/AccordionGroup.test.js
Fix in controlled accordion group and comprobation of expanded accordion in tests.
> Accordion group fixes

- lib/src/common/variables.js
- lib/src/wizard/Wizard.jsx
Fixes in the Wizard component style colors.
> Wizard style fix

- lib/src/accordion-group/AccordionGroup.jsx
Fixes in the new style of the accordion group.
> Fixes in accordion group style

- app/src/pages/Sidenav.jsx
- app/src/pages/Slider.jsx
- app/src/pages/Spinner.jsx
- app/src/pages/Switch.jsx
- app/src/pages/Table.jsx
- app/src/pages/ToggleGroup.jsx
- app/src/pages/Wizard.jsx
- lib/src/ThemeContext.js
- lib/src/common/variables.js
- lib/src/layout/ApplicationLayout.jsx
- lib/src/sidenav/Sidenav.jsx
- lib/src/slider/Slider.jsx
- lib/src/spinner/Spinner.jsx
- lib/src/switch/Switch.jsx
- lib/src/table/Table.jsx
- lib/src/textarea/Textarea.jsx
- lib/src/toggle-group/ToggleGroup.jsx
- lib/src/wizard/Wizard.jsx
(Sidenav, Slider, Spinner, Switch, Table, ToggleGroup, Wizard, Textarea and ApplicationLayout)
> New tokens approach for some components

- app/src/pages/Tabs.jsx
- lib/src/tabs/Tabs.jsx
> Style fix in tabs

- app/src/pages/Card.jsx
- docs/src/pages/components/cdk-components/card/api.jsx
- lib/src/card/Card.jsx
Fixed issue related to card image not been optional and new prop added to this component called _contentPadding_.
> Fix issue #237 and new Card prop added

- docs/src/pages/themeBuilder/test/colorpicker.test.js
- docs/src/pages/themeBuilder/test/component.test.js
- docs/src/pages/themeBuilder/test/import.test.js
- docs/src/pages/themeBuilder/test/jsonview.test.js
Added tests for theme builder tool.
> Theme builder tests

- docs/src/pages/themeBuilder/JSONView.jsx
- docs/src/pages/themeBuilder/components/ComponentPreview.jsx
- docs/src/pages/themeBuilder/components/ThemeInputsConfig.jsx
- lib/src/common/variables.js
- lib/src/link/Link.jsx
Issue #246 fixed (type="button" added in component Link when it's rendered as a button) and other minor behaviours resolved:
- Fixed bug in responsive menu text at component Header.
- Link component font-size fixed.
- Improved and fixed scroll in theme-builder.
> Fixing issue #246 and other minor things

- lib/src/tabs/Tabs.jsx
> [Patch] Fixed warning oneOfType

- docs/src/pages/themeBuilder/ImportDialog.jsx
- docs/src/pages/themeBuilder/ThemeBuilder.jsx
- docs/src/pages/themeBuilder/themes/DefaultTheme.json
Now the theme builder is able to import both advanced and default themes and distinguish between them.
> Improved import functionality in theme-builder

- docs/src/pages/themeBuilder/themes/AdvancedTheme.json
- docs/src/pages/themeBuilder/themes/schemas/Advanced.schema.json
- lib/src/common/variables.js
- lib/src/footer/Footer.jsx
SocialIconWidth and SocialIconHeight replaced by SocialIconSize.
Footer content is now adaptive when the user changes the MinHeight token.
> [Minor] Tokens fixes in Footer component

- lib/src/chip/Chip.jsx
> [Patch] Fixed issue #338 about onClickSuffix in Chip component

- docs/src/pages/themeBuilder/components/widgets/AlphaValueInput.jsx
- docs/src/pages/themeBuilder/components/widgets/BorderWidthInput.jsx
- docs/src/pages/themeBuilder/components/widgets/FontFamily.jsx
- docs/src/pages/themeBuilder/components/widgets/IntegerInput.jsx
- docs/src/pages/themeBuilder/components/widgets/LengthInput.jsx
- docs/src/pages/themeBuilder/components/widgets/LogoConfig.jsx
Some theme inputs widgets were not resetting correctly.
> Fix reset theme inputs

- docs/src/pages/themeBuilder/themes/AdvancedTheme.json
- lib/src/common/variables.js
- lib/src/link/Link.jsx
Fixed problem with Link's underline which produced the surounding text to displace when it was hovered.
> Fixed the displacement caused by Link's underline

- lib/src/checkbox/Checkbox.jsx
Added accesibility attributes to Checkbox component. Issue #332
> [Patch] Checkbox accesibility #332

- lib/src/dropdown/Dropdown.jsx
Fixed #281 related with null ref.current in Dropdown useEffect function.
> [Patch] Fixed issue #281

- lib/src/file-input/FileItem.jsx
- Added alt to image preview.
- Added aria-label to icon preview.
- Added aria-label to delete icon, specifying the name of the file to remove.
> [Patch] Added accessibility attributes to file input.

- lib/src/file-input/FileInput.jsx
- lib/src/new-input-text/NewInputText.jsx
- lib/src/new-textarea/NewTextarea.jsx
Id creation change in text input, textarea and file input in order to avoid id change in every render.
> [Patch] Change on ids creation.

- lib/src/alert/Alert.jsx
- Added display: block for fillParent and fixed sizes.
- Added box-sizing: border-box.
- Removed width and max-width in case it is fillParent size.
> [Patch] Fix alert size.

- docs/src/pages/themeBuilder/components/previews/Button.jsx
- docs/src/pages/themeBuilder/components/previews/Checkbox.jsx
- docs/src/pages/themeBuilder/components/previews/Date.jsx
- docs/src/pages/themeBuilder/components/previews/InputText.jsx
- docs/src/pages/themeBuilder/components/previews/NewDate.jsx
- docs/src/pages/themeBuilder/components/previews/NewInputText.jsx
- docs/src/pages/themeBuilder/components/previews/NewTextarea.jsx
- docs/src/pages/themeBuilder/components/previews/ProgressBar.jsx
- docs/src/pages/themeBuilder/components/previews/RadioButton.jsx
- docs/src/pages/themeBuilder/components/previews/Select.jsx
- docs/src/pages/themeBuilder/components/previews/Slider.jsx
- docs/src/pages/themeBuilder/components/previews/Spinner.jsx
- docs/src/pages/themeBuilder/components/previews/Switch.jsx
- docs/src/pages/themeBuilder/components/previews/Textarea.jsx
All on dark examples of the theme builder has been commented. We will work in the future on the on dark tokens.
> [Minor] On dark theme builder examples removed.

- app/src/pages/Date.jsx
- docs/src/pages/components/cdk-components/date/examples/controlledDate.js
- docs/src/pages/components/cdk-components/date/examples/sized.js
- docs/src/pages/components/cdk-components/date/examples/uncontrolledDate.js
- docs/src/pages/themeBuilder/components/previews/Date.jsx
- lib/src/date/Date.jsx
- lib/src/main.js
- lib/test/Date.test.js
- Renamed `DxcDate` export to `V3DxcDate`.
> [Major] Rename DxcDate to V3DxcDate.

- app/src/pages/Heading.jsx
- docs/src/pages/components/cdk-components/heading/Heading.jsx
- docs/src/pages/components/cdk-components/heading/api.jsx
- docs/src/pages/components/cdk-components/heading/examples/asHeadings.js
- lib/src/heading/Heading.jsx
- lib/test/Heading.test.js
- Added `as` prop to Heading component.
- Updated Heading documentation.
- Updated Heading examples.
- Updated Heading test.
> [Minor] Added as prop to Heading.

- docs/src/pages/components/cdk-components/V3Select/V3Select.jsx
- docs/src/pages/components/cdk-components/V3Select/api.jsx
- docs/src/pages/components/cdk-components/select/Select.jsx
- docs/src/pages/components/cdk-components/select/api.jsx
- docs/src/pages/components/cdk-components/select/examples/controlledSelect.js
- docs/src/pages/components/cdk-components/select/examples/multipleSelect.js
- docs/src/pages/components/cdk-components/select/examples/uncontrolledSelect.js
- docs/src/pages/components/paths.js
- Added documentation page of the select with its props and examples.
> [Minor] Select documentation added.

- docs/src/pages/themeBuilder/themes/AdvancedTheme.json
- docs/src/pages/themeBuilder/themes/schemas/Advanced.schema.json
- lib/src/common/variables.js
- lib/src/file-input/FileItem.jsx
- lib/src/password-input/PasswordInput.jsx
- lib/src/text-input/TextInput.jsx
- Added `Show` title to the password icon if it is not visible and `Hide` if the password is visible.
- Changes in styles of the hover, focus and active of the file item's delete button.
> [Patch] Added title to password icon and change in styles of file input.

- app/src/pages/InputText.jsx
- docs/src/pages/components/cdk-components/dialog/examples/backgroundCloseDialog.js
- docs/src/pages/components/cdk-components/input-text/examples/autocomplete.js
- docs/src/pages/components/cdk-components/input-text/examples/controlledInputText.js
- docs/src/pages/components/cdk-components/input-text/examples/darkThemedInputText.js
- docs/src/pages/components/cdk-components/input-text/examples/fillParentInputInputText.js
- docs/src/pages/components/cdk-components/input-text/examples/lebeledInputText.js
- docs/src/pages/components/cdk-components/input-text/examples/maskedInputText.js
- docs/src/pages/components/cdk-components/input-text/examples/sizedInputText.js
- docs/src/pages/components/cdk-components/input-text/examples/uncontrolledInputText.js
- docs/src/pages/themeBuilder/components/previews/Dialog.jsx
- docs/src/pages/themeBuilder/components/previews/InputText.jsx
- lib/src/date/Date.jsx
- lib/src/input-text/InputText.jsx
- lib/src/input-text/index.d.ts
- lib/src/main.d.ts
- lib/src/main.js
- lib/test/InputText.test.js
Rename DxcInputText to DxcInput again to avoid breaking change.
> Rename DxcInputText to DxcInput.

- lib/src/button/Button.stories.tsx
Change in button stories to use `Title`, `ExampleContainer` and `DarkSection`.
> Change in button stories.

- docs/src/pages/components/cdk-components/checkbox/api.jsx
- docs/src/pages/components/cdk-components/radio/api.jsx
- lib/src/checkbox/types.ts
- Label prop is required.
- Remove Size type from `types.ts` file.
- Change type of `value` prop to string in documentation.
- Remove object type of `size` prop in documentation.
- Change type of `value` prop to string in documentation.
> Types review

- lib/.storybook/preview.js
- lib/src/box/Box.stories.jsx
Added stories for `Box` component.
Added `font-family` styles.
> Added box stories

- lib/src/paginator/Paginator.stories.tsx
> Added Paginator stories

- lib/src/radio/Radio.stories.tsx
Closes #532 
Focus state is showed in an unique case since we need user events.
> Added Radio stories

- lib/src/button/Button.stories.tsx
- lib/src/password-input/PasswordInput.stories.jsx
- lib/src/tag/Tag.jsx
- lib/src/tag/Tag.stories.jsx
- Added tag stories.
- Fix fillParent size.
> Added tag stories

- lib/src/slider/Slider.stories.tsx
- lib/src/slider/types.ts
`labelFormatCallback` type is also fixed in this PR.
> Added Slider stories

- lib/src/toggle-group/ToggleGroup.stories.tsx
> Added ToggleGroup stories

- lib/src/chip/Chip.stories.tsx
> Added Chip stories

- lib/src/header/Header.stories.tsx
> Added Header stories

- lib/src/tabs/Tabs.tsx
> [Patch] Disabled tabs focus, hover and active styles

- docs/src/pages/components/cdk-components/text-input/api.jsx
- lib/src/number-input/NumberInputContext.js
- lib/src/number-input/NumberInputContext.tsx
- lib/src/number-input/numberInputContextTypes.ts
- lib/src/password-input/types.ts
- lib/src/slider/Slider.tsx
- lib/src/text-input/TextInput.tsx
- lib/src/text-input/types.tsx
- Added textInput types.
- Modified input value of the slider to be passed as a string instead of a number.
> Added textInput types.

- lib/src/table/Table.tsx
> [Patch] Horizontal scroll in table component

- app/src/pages/PasswordInput.jsx
- app/src/pages/TextInput.jsx
- docs/src/pages/components/cdk-components/password-input/api.jsx
- docs/src/pages/components/cdk-components/password-input/examples/customErrorsPasswordInput.js
- docs/src/pages/components/cdk-components/password-input/examples/lengthPasswordInput.js
- docs/src/pages/components/cdk-components/text-input/api.jsx
- docs/src/pages/components/cdk-components/text-input/examples/customErrorsTextInput.js
- docs/src/pages/components/cdk-components/text-input/examples/lengthTextInput.js
- lib/src/password-input/PasswordInput.tsx
- lib/src/password-input/types.ts
- lib/src/text-input/TextInput.tsx
- lib/src/text-input/types.tsx
- lib/test/TextInput.test.js
- Change `length` prop by `minLength` and `maxLength` props in `TextInput` and `PasswordInput`.
- Api documentation updated for both components.
- App examples updated for both components.
- Documentation examples updated for both components.
> [Major] Change length by minLength and maxLength in TextInput and PasswordInput.

- app/src/pages/Textarea.jsx
- docs/src/pages/components/cdk-components/textarea/api.jsx
- docs/src/pages/components/cdk-components/textarea/examples/customErrorsTextarea.js
- docs/src/pages/components/cdk-components/textarea/examples/lengthTextarea.js
- lib/src/textarea/Textarea.jsx
- lib/src/textarea/index.d.ts
- lib/test/Textarea.test.js
- Change `length` prop by `minLength` and `maxLength` props in `Textarea`.
- Api documentation updated.
- App examples updated.
- Documentation examples updated.
> [Major] Change length by minLength and maxLength in Textarea.

- lib/src/common/variables.js
- lib/src/file-input/FileInput.tsx
- lib/src/file-input/FileItem.tsx
- lib/src/select/Select.jsx
Summary
- Updated clear focus.
- Error message fixed in single file selection.
- Single file selection alignment fixed
> File-input visual fixes

- lib/src/dropdown/types.ts
- lib/src/footer/types.ts
- lib/src/resultsetTable/types.ts
- lib/src/tabs/types.ts
- lib/src/toggle-group/types.ts
- lib/src/wizard/types.ts
Changing old type for arrays (`[T, ...T]`), which was causing problems, to a less restrictive one (`T[]`).
> Change array type in some components

- lib/src/wizard/Wizard.tsx
> [Patch] Selected step when disabled style

- lib/src/accordion-group/types.ts
- lib/src/accordion/Accordion.stories.tsx
- lib/src/accordion/types.ts
Summary:
- Labels are now mandatory in both Accordion and Accordion Group Accordions.
- Added Accordion stories.
> Added Accordion stories

- docs/src/pages/components/cdk-components/tabs/api.jsx
- docs/src/pages/components/cdk-components/tabs/examples/iconsTabs.js
- docs/src/pages/components/cdk-components/tabs/examples/notificationTabs.js
- lib/src/tabs/Tabs.stories.tsx
- lib/src/tabs/Tabs.tsx
- lib/src/tabs/types.ts
- lib/test/Tabs.test.js
- Remove iconSrc in Tabs component.
- Fix stories.
> [Minor] Remove iconSrc from Tabs

- lib/src/bleed/Bleed.tsx
- lib/src/inset/Inset.tsx
- lib/src/list/List.tsx
- lib/src/list/types.tsx
- lib/src/row/Row.stories.tsx
- lib/src/row/Row.tsx
- lib/src/row/types.tsx
- lib/src/stack/Stack.stories.tsx
- lib/src/stack/Stack.tsx
- lib/src/stack/types.tsx
- Stack, Row and List types moved to an external file.
- Change in Stack, Row and List stories.
> Changes in Stack, Row and List

- lib/src/list/List.tsx
- lib/src/text/Text.tsx
* Add a `line-height` of `1.5em` to the text component
* Update list component type item `margin-top` 
Closes #784
> Add line-height property to text component

- docs/src/pages/components/cdk-components/chip/api.jsx
- docs/src/pages/components/cdk-components/chip/examples/suffixPrefix.js
- lib/src/chip/Chip.stories.tsx
- lib/src/chip/Chip.tsx
- lib/src/chip/types.ts
- lib/test/Chip.test.js
- Remove iconSrc in Chip component.
- Fix stories and tests.
> [Minor] Remove iconSrc from Chip

- docs/src/pages/components/cdk-components/accordion-group/accordionSingleApi.jsx
- docs/src/pages/components/cdk-components/accordion/api.jsx
- lib/src/accordion-group/types.ts
- lib/src/accordion/Accordion.tsx
- lib/src/accordion/types.ts
- Remove iconSrc from Accordion and Accordion group components.
> [Minor] Remove iconSrc from Accordion and Accordion group

- docs/src/pages/components/cdk-components/chip/api.jsx
- docs/src/pages/components/cdk-components/dropdown/api.jsx
- docs/src/pages/components/cdk-components/dropdown/examples/imagesDropdown.js
- lib/src/dropdown/Dropdown.stories.tsx
- lib/src/dropdown/Dropdown.tsx
- lib/src/dropdown/types.ts
- lib/test/Dropdown.test.js
- Remove iconSrc  from Dropdown component.
- Fix stories and tests.
> [Minor] Remove iconSrc from Dropdown

- docs/src/pages/components/cdk-components/radio-group/RadioGroup.jsx
- docs/src/pages/components/cdk-components/radio-group/api.jsx
- docs/src/pages/components/cdk-components/radio-group/examples/basicUsage.js
- docs/src/pages/components/cdk-components/radio-group/examples/controlled.js
- docs/src/pages/components/cdk-components/radio-group/examples/optional.js
- docs/src/pages/components/cdk-components/radio-group/examples/stacking.js
- docs/src/pages/components/paths.js
- lib/src/main.ts
Summary:
- New radio group is now been exported and can be used.
- Added first docs.
> Added new Radio Group documentation

- docs/src/pages/components/cdk-components/link/api.jsx
- lib/src/link/Link.stories.tsx
- lib/src/link/Link.tsx
- lib/src/link/types.ts
- Remove iconSrc from Link component.
- Fix stories.
> [Minor] Remove iconSrc from Link

- lib/src/accordion/Accordion.tsx
- lib/src/common/variables.js
- lib/src/dialog/Dialog.tsx
- lib/src/footer/Footer.tsx
- lib/src/header/Header.stories.tsx
- lib/src/header/Header.test.js
- lib/src/header/Header.tsx
- lib/src/layout/ApplicationLayout.tsx
- Update responsiveSizes in `variables.js`.
- Delete unused responsiveSizes from Accordion component.
- Use of media queries in Dialog, Footer, Header and Application Layout components.
- Viewports and other fixes in Header stories.
Closes #825
> [Major] New breakpoint values

- lib/src/button/Button.tsx
- lib/src/select/Listbox.tsx
- lib/src/select/Option.tsx
- lib/src/select/Select.tsx
- lib/src/select/listbox/Listbox.tsx
- lib/src/select/types.ts
Summary:
1. Fix issue regarding Button's label when a component with defined z-index was over the mentioned component.
_Previous behaviour:_
_After fix:_
2. **Select component refactor.** Listbox element extracted to an inner component for performance and code improvements.
3. Now each element of the listbox has a single key to avoid React warnings.
> Fix Button `z-index` and Select `listbox` refactor

- docs/src/pages/components/paths.js
Tag changes from **Layout** component to **Utilities** component
> Update Tag categorization

- lib/src/wizard/Wizard.tsx
> [Patch] Wizard margin overflow

- app/src/pages/Checkbox.jsx
- docs/src/pages/components/cdk-components/checkbox/api.jsx
- docs/src/pages/components/cdk-components/checkbox/examples/basicCheckbox.js
- docs/src/pages/components/cdk-components/checkbox/examples/labelPosition.js
- docs/src/pages/components/cdk-components/radio-group/examples/optional.js
- lib/src/checkbox/Checkbox.stories.tsx
- lib/src/checkbox/Checkbox.tsx
- lib/src/checkbox/types.ts
1. Removed `required` prop from Checkbox component.
2. Added `optional` prop to Checkbox component.
> [Major] Replace required prop with optional in Checkbox

- app/src/pages/Switch.jsx
- docs/src/pages/components/cdk-components/checkbox/api.jsx
- docs/src/pages/components/cdk-components/switch/api.jsx
- docs/src/pages/components/cdk-components/switch/examples/basicSwitch.js
- docs/src/pages/components/cdk-components/switch/examples/labelPositionSwitch.js
- lib/src/checkbox/types.ts
- lib/src/switch/Switch.stories.tsx
- lib/src/switch/Switch.tsx
- lib/src/switch/types.ts
1. Removed `required` prop from Switch component.
2. Added `optional` prop to Switch component.
> [Major] Replace required prop with optional in Switch

- app/src/pages/Accordion.jsx
- app/src/pages/AccordionGroup.jsx
- app/src/pages/Button.jsx
- app/src/pages/Checkbox.jsx
- app/src/pages/Chip.jsx
- app/src/pages/Dropdown.jsx
- app/src/pages/Footer.jsx
- app/src/pages/Header.jsx
- app/src/pages/Paginator.jsx
- app/src/pages/ProgressBar.jsx
- app/src/pages/Radio.jsx
- app/src/pages/Sidenav.jsx
- app/src/pages/Slider.jsx
- app/src/pages/Spinner.jsx
- app/src/pages/Switch.jsx
- app/src/pages/Table.jsx
- app/src/pages/Tabs.jsx
- app/src/pages/ToggleGroup.jsx
- app/src/pages/Wizard.jsx
- docs/src/App.jsx
- docs/src/pages/overview/Overview.jsx
- docs/src/pages/themeBuilder/components/ComponentPreview.jsx
- lib/.storybook/preview.js
- lib/src/HalstackContext.tsx
- lib/src/accordion/Accordion.stories.tsx
- lib/src/main.ts
- lib/src/useTheme.tsx
> Renaming ThemeContext and ThemeProvider to HalstackContext and HalstackProvider

- docs/src/pages/components/cdk-components/applicationLayout/examples/default.js
Now the application layout is working fine:
> [Patch] Fix application layout example

- lib/src/quick-nav-container/QuickNavContainer.tsx
- Fix sticky position.
- Add overflow to the quick nav.
> Fix sticky position in quickNav

- website/pages/_app.tsx
- website/screens/common/DocFooter.tsx
- website/screens/common/PageHeading.tsx
- website/screens/common/QuickNavContainer.tsx
- website/screens/common/QuickNavContainerLayout.tsx
- website/screens/principles/themes/ThemesPage.tsx
- Make quickNavContainer in site responsive.
- Fix themes page.
> QuicknavContainer in site responsive

- website/pages/components/chip/index.tsx
- website/pages/components/chip/usage.tsx
- website/screens/components/chip/ChipPageLayout.tsx
- website/screens/components/chip/code/ChipCodePage.tsx
- website/screens/components/chip/code/examples/basicUsage.ts
- website/screens/components/chip/usage/ChipUsagePage.tsx
Closes [#995](https://github.com/dxc-technology/halstack-react/issues/995).
> Added Chip code page

- docs/src/pages/components/cdk-components/progressBar/api.jsx
- lib/src/progress-bar/ProgressBar.stories.jsx
- lib/src/progress-bar/ProgressBar.tsx
> [Major] Changed default value of overlay prop in progressBar

- lib/src/layout/ApplicationLayout.tsx
- lib/src/layout/Icons.tsx
- lib/src/layout/types.ts
- website/pages/components/application-layout/index.tsx
- website/screens/components/application-layout/ApplicationLayoutPageLayout.tsx
- website/screens/components/application-layout/code/ApplicationLayoutCodePage.tsx
Summary:
- Removed outdated **Usage** tab.
- Added new Code tab.
> Added Application Layout documentation

- lib/src/layout/ApplicationLayout.tsx
- website/package.json
- website/pages/_app.tsx
- website/screens/common/sidenav/Sidenav.tsx
- website/screens/common/sidenav/SidenavComponents.tsx
The new website now uses the current version of the Application Layout.
> Update website with the new Application Layout

- docs/src/pages/components/cdk-components/applicationLayout/ApplicationLayout.jsx
- docs/src/pages/components/cdk-components/applicationLayout/api.jsx
- docs/src/pages/components/common/ComponentDoc.jsx
- lib/src/layout/ApplicationLayout.tsx
Summary:
1. Updated Application Layout docs in the older site.
2. Some component updates based on recent real use.
> Update Application Layout docs in old site

- lib/src/card/Card.tsx
> [Patch] Focus outline fits Card size

- lib/src/layout/ApplicationLayout.tsx
Added label to hamburger button in application layout:
> Added label to hamburger in application layout

- website/screens/principles/localization/examples/translations.ts
Select is not showing any example.
Added useState and itemsPerPage to fixed it.
> Fixed example translation

- website/screens/common/example/Example.tsx
- website/screens/components/application-layout/code/ApplicationLayoutCodePage.tsx
Reverts dxc-technology/halstack-react#1163
> Revert "Change actions visibility in site examples"

- lib/src/inline/Inline.stories.tsx
- lib/src/inline/Inline.tsx
- Fix gap value when showing the divider.
- Fix divider height when using alignY.
- Changes in story examples.
> Inline component fixes

- lib/src/inline/Inline.tsx
- lib/src/stack/Stack.tsx
- Remove divider width (1px) from gap total value.
- Set default margin and padding to 0px.
- Fix gap value when dividier is shown.
> Stack and Inline style fixes

- lib/src/inline/Inline.stories.tsx
- lib/src/inline/Inline.tsx
Update Inline styles for more consistent behaviour regarding the other layout components.
> Fix Inline width for both flex and non-flex boxes

- docs/src/pages/components/Components.jsx
- lib/src/layout/ApplicationLayout.tsx
- lib/src/stack/Stack.tsx
- website/screens/common/sidenav/Sidenav.tsx
Summary:
1. Fixed #1201.
2. Update to Sidenav container styles (Application Layout) and improved in /website.
> [Minor] Application Layout: Sidenav and Dropdown menu improvements

- lib/src/wizard/Wizard.stories.tsx
- lib/src/wizard/Wizard.tsx
- lib/src/wizard/types.ts
Fixes [987](https://github.com/dxc-technology/halstack-react/issues/987). Also, removed the `@ts-nocheck` flag in the component.
> [Patch] Update Wizard focus behaviour

- lib/src/link/Link.stories.tsx
- lib/src/link/Link.tsx
Also added the case to storybook.
Closes #1218
> [Patch] Link with icon inline with text

- lib/src/slider/Slider.test.js
- lib/src/slider/Slider.tsx
Removing "&& value" from condition to accept value 0 in slider.
Created from #1264
> [Patch] fix Slider to accept zero

- website/package.json
- website/yarn.lock
Reverts dxc-technology/halstack-react#1292
> Revert "Updated cdk in website"

- README.md
- lib/README.md
Change links in the READMEs to new site.
> Change README links to /halstack

- website/package.json
Updated halstack version to the last one in the site.
> Update halstack version in site

- website/package.json
- website/screens/common/sidenav/SidenavLogo.tsx
- website/screens/overview/introduction/IntroductionPage.tsx
**Checklist**
**Purpose**
The introduction page on the website has a link to the current release documentation, but now it is not working fine in "next". Also, the tag that indicates the version of the documentation is not working as expected.
- Now we obtain the current release version from `versions.json` and append it to the link.
- Version tag is obtained from `basePath`.
> Website version fixes

- lib/src/checkbox/Checkbox.tsx
- lib/src/dropdown/Dropdown.test.js
- lib/src/dropdown/Dropdown.tsx
- lib/src/dropdown/DropdownMenuItem.tsx
- lib/src/tabs-nav/Tab.tsx
**Checklist**
Replace the `"Space"` key with `" "` in Checkbox, Dropdown and Navigation Tabs.
**Closes #1324**
> Replace `"Space"` key by `" "`

- .github/workflows/publish-release.yml
- scripts/release-website.js
**Checklist**
**Purpose**
Fix the error that we have in the Publish Release [workflow](https://github.com/dxc-technology/halstack-react/actions/runs/3188232724/jobs/5200651927).
Removed build process from YAML file and added directory to `website` in `publish-release` script.
> Fix website build in release-website script

- lib/src/slider/Slider.tsx
**Checklist**
**Purpose**
Marks should be above the track line of the slider.
Fixed to show the marks correctly. Added calculation to check if the marks are before or after the thumb to change their `z-index` value.
**Closes #1322**
> Fixed marks slider

- website/screens/components/button/specs/ButtonSpecsPage.tsx
- website/screens/components/dialog/specs/DialogSpecsPage.tsx
- website/screens/components/dropdown/specs/DropdownSpecsPage.tsx
- website/screens/components/select/specs/SelectSpecsPage.tsx
- website/screens/components/text-input/specs/TextInputSpecsPage.tsx
**Checklist**
**Purpose**
Match the common criteria of how our specification pages should look like.
The numbering of the titles of the Select specifications page has been fixed in order to match the rest of the components.
> Fix Select specifications page

- lib/src/password-input/PasswordInput.tsx
- lib/src/text-input/types.ts
**Checklist**
**Purpose**
Added `event.preventDefault()` to avoid that clicking on password action executes the submit inside a form.
If the password is used inside a form, when the action is clicked, it executes the submit.
**Closes** #1361
> Fix password action inside a form

- website/package.json
**Checklist**
**Purpose**
Haltsack react version updated to 7.0.0 in /website.
Haltsack react version updated to 7.0.0 in /website.
> Update website to 7.0.0 halstack-react version

- lib/src/dropdown/Dropdown.test.js
- lib/src/dropdown/Dropdown.tsx
**Checklist**
Use a relatively new Web Api called Resize Observer to "observe" the possible size changes of the dropdown trigger and keep updated as need the Listbox of the component.
[Resize Observer Web API](https://www.google.com/search?q=Resize+observer&rlz=1C1GCEU_esES944ES944&oq=Resize&aqs=chrome.1.69i59l3j69i57j69i59j69i65j69i60j69i61.3306j0j7&sourceid=chrome&ie=UTF-8)
**Closes #1374**
> New `ResizeObserver` added to Dropdown

- docs/src/pages/themeBuilder/themes/AdvancedTheme.json
- docs/src/pages/themeBuilder/themes/schemas/Advanced.schema.json
- lib/src/HalstackContext.tsx
- lib/src/common/variables.js
- website/screens/principles/themes/ThemesPage.tsx
**Checklist**
Removed unused token ```selectedFontColor```.
Added default theme inputs in theme page for quicknav.
**Closes #1381**
> Added default theme inputs in theme page for quicknav

- website/screens/principles/themes/ThemesPage.tsx
**Checklist**
Fixed default theme inputs in the documentation. Added the default theme input `optionFontColor` for the token `listOptionFontColor` and removed `listOptionFontColor` from the theme input `fontColor`.
**Closes #1382**
> Updated theme inputs for select component

- website/screens/principles/themes/ThemesPage.tsx
**Checklist**
Added theme input `fontColor` in the themes page with the token `labelFontColor`.
**Closes #1384**
> Added default theme input for switch in documentation

- lib/src/HalstackContext.tsx
- website/screens/principles/themes/ThemesPage.tsx
**Checklist**
Moved the token `selectedStepBorderColor` to the list of the theme input `baseColor`.
Fixed typo in HalstackContext.
**Closes #1385**
> Updated default theme input in wizard component

- lib/src/common/variables.js
- lib/src/slider/Slider.tsx
**Checklist**
Changed color for the token `totalLineColor` in slider component. Added opacity of 10% in the variables.
**Closes #1383**
> Changed color for totalLineColor token in slider

- website/package.json
- website/yarn.lock
**Checklist**
**Purpose**
Update cdk in website with last commit.
> Updated cdk in website

- app/src/pages/Accordion.jsx
- lib/package-lock.json
**Checklist**
**Purpose**
Updated package-lock as dependabot PR.
Updated package-lock as dependabot PR.
> Dependabot change

- website/package-lock.json
- website/package.json
- website/yarn.lock
**Checklist**
**Purpose**
Update the version of the Halstack dependency (`@dxc-technology/halstack-react`) to the latest version released (8.0.0).
Update /website Halstack dependency to the 8.0.0 release.
> Upgrade Halstack to the latest version of the CDK

- website/package.json
**Checklist**
**Purpose**
Update site with the last version of the cdk.
Update site with the last version of the cdk.
> Updated cdk version in website

- .github/workflows/chromatic.yml
- lib/src/accordion/Accordion.stories.tsx
**Checklist**
**Purpose**
If applicable, add screenshots to help explain your change.
> Jsuarezgonz testing

- website/package.json
**Checklist**
**Purpose**
Update cdk version to the last one in website.
Update cdk version to the last one in website.
> Update cdk version in website

- website/screens/principles/localization/LocalizationPage.tsx
**Checklist**
**Purpose**
Fix for issue 1508
Fixing broken link.
If applicable, add screenshots to help explain your change.
Closes #1508
> Fix for OC-13414

- app/package-lock.json
- app/src/paths.js
- lib/package-lock.json
**Checklist**
**Purpose**
After some issues were reported with the user experience of using /the app, we decided to review it and apply some changes.
1. Updated package-lock in /app to fix some launching problems. As it stands, when following the steps on the README.txt, /app was throwing errors:
Updating the packages of the package-lock.json file fixed this issue.
2. /app console warnings were also removed.
> Updates to package dependencies & improved user experience

- website/package-lock.json
- website/package.json
- website/yarn.lock
**Checklist**
**Purpose**
Update cdk version to 9 in website.
Cdk version updated to 9 in website.
> Update cdk in website to v9

- website/screens/components/typography/code/TypographyCodePage.tsx
**Checklist**
Fixing some typos in the Typography component code page.
**Closes #1530**
> Fix typos in Typography code page

- lib/src/HalstackContext.tsx
**Checklist**
**Purpose**
Fix tokens in HalstackContext.
Fix tokens in HalstackContext.
> Fix HalstackContext tokens

- .github/workflows/publish-release.yml
- app/src/pages/Dialog.jsx
- app/src/pages/Dropdown.jsx
- website/package.json
- website/screens/common/sidenav/SidenavLogo.tsx
- website/screens/theme-generator/ThemeGenerator.tsx
- website/screens/theme-generator/components/previews/Header.tsx
- website/yarn.lock
**Checklist**
- Change website cdk version to `9.0.1`.
- Type fix in dropdown preview in theme generator.
- Change in tag version to show installed version of cdk.
- SidenavLogo prop changed to `subtitle`.
> Change website cdk version to 9.0.1 and change in tag version

- scripts/package-lock.json
- scripts/package.json
**Checklist**
**Purpose**
There is a vulnerability in the folder `scripts`.
Fixed `xml2js`. As a result of this vulnerability fixed, `aws-sdk` dependency was updated.
> Fixed vulnerability

- website/package-lock.json
- website/package.json
- website/yarn.lock
**Checklist**
Update cdk version in website to `9.1.0`.
> Update website version to 9.1.0

- lib/src/bulleted-list/BulletedList.stories.tsx
- lib/src/bulleted-list/BulletedList.tsx
**Checklist**
Now icon can be added as a `path` in Bulleted list component.
**Closes #1605**
> Icon in bulleted list accepts a path

- lib/src/bulleted-list/BulletedList.tsx
- lib/src/bulleted-list/types.ts
**Checklist**
Change in types so that when it is `icon` type requires an `icon`.
Change in `SVG` type.
> Change in Bulleted list types

- lib/src/utils/FocusLock.tsx
**Checklist**
Trying to fix Focus Lock issues with version 2.2.5 of the `nwsapi` jsdom library.
**Closes #1614**
> Focus Lock selectors update

- lib/src/accordion-group/AccordionGroup.tsx
- lib/src/accordion-group/AccordionGroupAccordion.tsx
- website/screens/components/accordion/code/AccordionCodePage.tsx
**Checklist**
Summary:
- Exporting Accordion Group's context for UXPin purposes.
- Removing children type filtering. We let the typing and the documentation teach the users.
- Updated documentation.
> Accordion group update

- lib/src/nav-tabs/NavTabs.stories.tsx
- lib/src/nav-tabs/NavTabs.tsx
- lib/src/nav-tabs/Tab.tsx
- lib/src/nav-tabs/types.ts
- website/screens/components/nav-tabs/code/NavTabsCodePage.tsx
**Checklist**
Some code updates and minor styling tweaks to improve the Nav Tabs component as a whole.
> Nav Tabs refactor and improvements

- lib/src/layout/ApplicationLayout.tsx
**Checklist**
- Add background color `white` to Main in Application layout.
- Change `div` to `main` in Main in Application layout.
> Application layout - Main changes

- website/next.config.js
- website/package-lock.json
- website/package.json
- website/pages/_document.tsx
- website/screens/common/HeadingLink.tsx
- website/screens/overview/introduction/IntroductionPage.tsx
- website/yarn.lock
**Checklist**
Trying to fix ADA compliance critical issues:
- Include the `lang` attribute in the `<html>` element.
- Add `title` to heading links.
I've also updated the `halstack-react` package version.
**Closes #1643**
> ADA critical issues fixes

- website/package-lock.json
- website/screens/components/grid/code/GridCodePage.tsx
- website/screens/components/grid/code/examples/layout.tsx
- website/screens/theme-generator/components/previews/Footer.tsx
- website/yarn.lock
**Checklist**
Update `@dxc-technology/halstack-react` package in website to `next` version. A few pages needed to be updated.
> Update website to latest version

- website/screens/overview/releases/ReleasesPage.tsx
**Checklist**
Added a link to the 'Major released versions' section on Halstack /releases page.
> Adding Halstack 10 to major released versions

- website/package-lock.json
- website/package.json
- website/screens/common/QuickNavContainer.tsx
- website/screens/common/TabsPageLayout.tsx
- website/screens/components/dialog/code/examples/backgroundClick.ts
- website/screens/components/dialog/code/examples/basicUsage.ts
- website/screens/components/dialog/code/examples/withContent.ts
- website/screens/theme-generator/ImportDialog.tsx
- website/screens/theme-generator/components/previews/Dialog.tsx
- website/yarn.lock
**Checklist**
**Purpose**
To see the latest changes made on the Toggle Group component.
- Update `@dxc-technology/halstack-react` from `10.0.0` to the `next` version. 
- Also, some improvements were made to the Halstack site in responsive scenarios.
- Dialog examples updated due to the removal of the `padding` prop.
> Halstack website updates

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- lib/README.md
- website/README.md
**Checklist**
**Purpose and description**
Update all our readme files and issue/pull request templates to stay up with our current technology choices, project structure and team standards. The object is to distribute better all the information so anyone can understand Halstack's main project.
**Closes #1349**
> Updates to all the READMEs and templates

- lib/src/common/variables.ts
- lib/src/image/Image.tsx
- website/package-lock.json
- website/screens/components/heading/code/examples/basicUsage.ts
- website/screens/components/image/code/ImageCodePage.tsx
- website/screens/components/image/code/examples/basicUsage.ts
- website/screens/principles/themes/examples/defaultAdvancedTheme.ts
- website/screens/theme-generator/themes/advanced-theme.json
- website/screens/theme-generator/themes/schemas/advanced.schema.json
- website/yarn.lock
**Checklist**
**Purpose**
Completing the development of the Image component.
Added an example for the Image component documentation and also new tokens for this same component.
> New Image tokens and examples added

- website/package-lock.json
- website/package.json
Updated the version of halstack-react to be displayed correctly on the site.
> Updated halstack-react version

- lib/src/nav-tabs/Tab.tsx
**Checklist**
Remove underline of the nav tabs text when they are selected.
**Closes #1454**
> Remove underline in nav tabs when selection

- lib/src/chip/Chip.tsx
**Checklist**
Chip is not using `focusBorderStyle` token.
> Update Chip to use solid token

- website/package-lock.json
- website/package.json
- website/screens/common/sidenav/SidenavLogo.tsx
- website/screens/overview/releases/ReleasesPage.tsx
- website/yarn.lock
**Checklist**
Updated `@dxc-technology/halstack-react` to the eleventh release.
> Halstack 11 released on website

- .github/workflows/publish-next.yml
- lib/README.md
**Checklist**
**Purpose**
This should fix the error we are getting in GitHub actions.
> Fixing publish next workflow

- website/screens/components/progress-bar/specs/ProgressBarSpecsPage.tsx
**Checklist**
**Purpose**
Add the uppercase token in the progressbar specifications.
The Progressbar component was outdated in our documentation, so the purpose of this PR is to update the specifications of the Progressbar by adding the uppercase token of its label element.
> Add uppercase in progressbar specs

- website/screens/theme-generator/themes/schemas/advanced.schema.json
**Checklist**
Fixing the advanced theme generator schema to make it work again. This error was caused by the token `overlayFontColor` which was outdated in the schema.
> Advanced theme schema update

- website/package-lock.json
> Update website to latest version.

- lib/src/utils/FocusLock.tsx
**Checklist**
Popups inside dialog were not being displayed correctly. This has been fixed ensuring that Popups are being properly identified inside the DOM.
(Related to PR #1817)
**Closes #1809**
> Fixed popups not working inside Dialog

- lib/src/badge/types.tsx
**Checklist**
Small change in badge types.
> Small change in badge types

- lib/src/container/Container.tsx
**Checklist**
The `border-color` property was not been applied properly due to a typo.
> Update Container border bug

- lib/src/table/ActionsCell.tsx
**Checklist**
Fixed a bug when there was no dropdown in actions.
Check out [actionsCell PR](https://github.com/dxc-technology/halstack-react/pull/1836)
> Fixed actionsCell bug

- lib/src/badge/Badge.stories.tsx
- lib/src/badge/Badge.tsx
**Checklist**
Added `box-sizing: border-box` to fix badge height.
> Fix badge height

- lib/src/table/ActionsCell.tsx
**Checklist**
**Purpose**
Aligning actions to the center of the cell.
> Aligning actions to the center

- website/package-lock.json
Update halstack version in /website.
> Update halstack version in website

- .github/workflows/push-catalog-s3.yml
Update node version to 18 in `push-catalog` workflow.
> Update node in push-catalog script

- lib/src/main.ts
**Checklist**
Related to #1835, DxcDivider was not being exported.
> Added DxcDivider component export

- lib/src/button/Button.stories.tsx
- lib/src/button/Button.tsx
- lib/src/button/types.ts
**Checklist**
**Purpose**
Added new icon component to the button and removed support to img url.
> Icon added to the button

- lib/src/dropdown/Dropdown.stories.tsx
- lib/src/dropdown/Dropdown.tsx
- lib/src/dropdown/DropdownMenuItem.tsx
- lib/src/dropdown/types.ts
**Checklist**
**Purpose**
New icon implemented in the dropdown component
> Icon implemented in the dropdown

- website/package-lock.json
- website/screens/components/button/code/ButtonCodePage.tsx
- website/screens/components/button/code/examples/icons.ts
- website/screens/components/button/usage/examples/iconUsage.ts
**Checklist**
**Purpose**
Button documentation updated to include the new icon.
> Button Icon documentation updated

- lib/src/action-icon/ActionIcon.stories.tsx
- lib/src/action-icon/ActionIcon.tsx
- lib/src/action-icon/types.ts
- lib/src/resultset-table/ResultsetTable.stories.tsx
- lib/src/table/Table.stories.tsx
- lib/src/table/Table.tsx
- lib/src/table/types.ts
- lib/src/text-input/TextInput.stories.tsx
**Checklist**
**Purpose**
New Icon component implemented in the actionIcon and actionsCell
> Icon implemented in the actions cell

- website/package-lock.json
- website/screens/components/accordion/code/AccordionCodePage.tsx
- website/screens/components/accordion/code/examples/icons.ts
**Checklist**
**Purpose**
Accordion documentation updated to include the new icon.
> Accordion's icon doc updated

- lib/src/bulleted-list/BulletedList.stories.tsx
- lib/src/bulleted-list/BulletedList.tsx
**Checklist**
**Purpose**
Icon component implemented in the bulleted list
> Icon implemented in the bulleted list

- lib/src/chip/Chip.stories.tsx
- lib/src/chip/Chip.test.js
- lib/src/chip/Chip.tsx
**Checklist**
**Purpose**
Chip icon prop updated with the new Icon implementation.
> Updating chip icon prop

- lib/src/link/Link.stories.tsx
- lib/src/link/Link.tsx
- lib/src/link/types.ts
**Checklist**
Link icon prop updated with the new Icon implementation.
> Change icon prop to use our component

- lib/src/footer/Footer.stories.tsx
- lib/src/footer/Footer.test.js
- lib/src/footer/Footer.tsx
- lib/src/footer/types.ts
**Checklist**
Icon added in our Footer component.
> Icon added to the Footer

- lib/src/file-input/FileInput.test.js
- lib/src/file-input/FileInput.tsx
- lib/src/file-input/FileItem.tsx
**Checklist**
**Purpose**
New icon implemented in the fileInput
> Icon implemented in fileInput

- website/package-lock.json
- website/screens/components/bulleted-list/code/BulletedListCodePage.tsx
**Checklist**
**Purpose**
Updated BulletedList icon prop documentation.
> Updating bulletedList icon doc

- lib/src/badge/Badge.stories.tsx
- lib/src/badge/Badge.tsx
- lib/src/badge/types.tsx
- website/pages/components/badge/index.tsx
**Checklist**
Icon added to the Badge component.
> Icon added to the Badge

- lib/src/header/Header.tsx
**Checklist**
**Purpose**
Changes in closeIcon and hamburguerIcon to use the new component.
> Changes in closeIcon and hamburguerIcon to use the new component

- lib/src/tag/Tag.stories.tsx
- lib/src/tag/Tag.test.js
- lib/src/tag/Tag.tsx
- lib/src/tag/types.ts
**Checklist**
Icon added to the Tag component.
> Icon added to the Tag

- lib/src/nav-tabs/NavTabs.accessibility.test.js
- lib/src/nav-tabs/NavTabs.stories.tsx
- lib/src/nav-tabs/NavTabs.test.js
- lib/src/nav-tabs/Tab.tsx
- lib/src/nav-tabs/types.ts
> Using DxcIcons in NavTabs

- lib/src/wizard/Wizard.stories.tsx
- lib/src/wizard/Wizard.tsx
- lib/src/wizard/types.ts
**Checklist**
**Purpose**
New Icon component was added to the wizard.
> Icon component added to the Wizard component

- website/screens/components/sidenav/code/SidenavCodePage.tsx
**Checklist**
**Purpose**
Documentarion related to the icon prop in the sidenav updated.
> Sidenav icon prop documentation updated

- app/package-lock.json
- lib/package-lock.json
**Checklist**
Resolve vulnerabilities after `npm audit fix`.
> Fix vulnerabilities

- website/package-lock.json
- website/screens/common/themes/advanced-theme.json
- website/screens/theme-generator/themes/schemas/advanced.schema.json
**Checklist**
**Purpose**
Dialog's closeIcon size token changed due to the new icon implementation.
The icon component is affected by the fontSize so width and height were
> Dialog's closeIcon size token changed due to the new icon implementation

- .github/workflows/publish-release.yml
**Checklist**
Fixing the release workflow by adding `babel` dependecy.
> Update publish release workflow

- lib/package-lock.json
- lib/package.json
- lib/src/slider/Slider.stories.tsx
**Checklist**
Summary of changes:
- Restored Slider stories.
- [storybook-addon-pseudo-states](https://github.com/chromaui/storybook-addon-pseudo-states) updated from version `2.1.2` to `3.0.1`, which contains the desired fix.
**Closes #1738**
> Adding missing Slider stories

- website/package-lock.json
- website/package.json
**Checklist**
**Purpose**
Update website to the latest version.
> updating website to 12.0.2

- website/package-lock.json
- website/package.json
- website/pages/_app.tsx
- website/pages/overview/component-lifecycle.tsx
- website/screens/common/StatusBadge.tsx
- website/screens/components/contextual-menu/code/ContextualMenuCodePage.tsx
- website/screens/components/contextual-menu/usage/ContextualMenuUsagePage.tsx
- website/screens/overview/component-lifecycle/ComponentLifecyclePage.tsx
**Checklist**
- Relocating component lifecycle page. It was under principles directory and it should be under overview.
- Adding the new item prop `selectedByDefault` to the Contextual Menu code page. Usage guidelines have also been added.
- Minor code updates.
> Site updates

- scripts/create-catalog.js
- website/package-lock.json
- website/package.json
**Checklist**
**Purpose**
We are currently struggling with the workflows ["Publish release"](https://github.com/dxc-technology/halstack-react/actions/workflows/publish-release.yml) and ["Publish Design system catalog"](https://github.com/dxc-technology/halstack-react/actions/workflows/push-catalog-s3.yml).
Updates:
- Fixed the `create-catalog.json` script. Now checks for the existence of the folder containing the catalogue. If it does not exist, it creates it.
- Added new `sharp` package to the website, which is now required for the next js proper build.
- Updated `@dxc-technology/halstack-react` to the latest release `12.1.0`.
> Fixing workflows

- website/screens/common/themes/advanced-theme.json
- website/screens/components/resultset-table/specs/ResultsetTableSpecsPage.tsx
- website/screens/components/table/specs/TableSpecsPage.tsx
- website/screens/theme-generator/components/previews/Table.tsx
- website/screens/theme-generator/themes/schemas/advanced.schema.json
**Checklist**
**Purpose**
Added missing doc related to the actionsCell tokens.
Closes #1976
> Added tokens related to the actions cell to the documentation

- .github/workflows/check-links.yml
- .lycheeignore
- README.md
**Checklist**
[lychee-action](https://github.com/lycheeverse/lychee-action) has been setup in our project to look for broken links. In case that there is any, it will automatically open a Issue regarding indicating what link is broken and where it is located.
**Closes #1972**
> Added link checker to github actions

- scripts/create-version.js
**Checklist**
The script was not able to create the directory.
To fix this issue now the script checks for the directory and if it does not exist it will create the directory before the version file.
> Fixed publish release workflow

- website/package-lock.json
- website/package.json
**Checklist**
Halstack-react updated to 12.2.0
> website update to 12.2.0

- lib/src/main.ts
**Checklist**
**Purpose**
DxcBarChart added as a exported component.
> BarChart added to the exports

- lib/src/resultset-table/ResultsetTable.tsx
- lib/src/resultset-table/types.ts
- website/screens/components/resultset-table/code/ResultsetTableCodePage.tsx
**Checklist**
**Purpose**
Support to sort by Date added to the resultsetTable
**Closes #2013 **
> Added Date support to resultsetTable sorting

- lib/src/container/Container.stories.tsx
- lib/src/main.ts
**Checklist**
Due to deciding to export the custom Tooltip component instead of only using it internally, it is required to export it from the library.
> Export tooltip component from Halstack

- website/screens/components/breadcrumbs/code/BreadcrumbsCodePage.tsx
- website/screens/components/bulleted-list/code/BulletedListCodePage.tsx
- website/screens/components/contextual-menu/code/ContextualMenuCodePage.tsx
- website/screens/components/flex/code/FlexCodePage.tsx
- website/screens/components/paragraph/code/ParagraphCodePage.tsx
- website/screens/components/quick-nav/code/QuickNavCodePage.tsx
- website/screens/components/status-light/code/StatusLightCodePage.tsx
**Checklist**
There were some missing "Required" badges and a typo in `DxcFlex`.
> Added missing information in documentation

- packages/lib/src/action-icon/ActionIcon.tsx
- turbo.json
**Checklist**
Trying to fix environment variable issues in website. Based on the guidelines of turborepo: https://turbo.build/repo/docs/crafting-your-repository/using-environment-variables.
> Adding environment variables for turbo

- CONTRIBUTING.md
- LOCAL.md
- README.md
- apps/website/screens/common/sidenav/SidenavLogo.tsx
- apps/website/screens/components/breadcrumbs/code/BreadcrumbsCodePage.tsx
- apps/website/screens/components/bulleted-list/code/BulletedListCodePage.tsx
- apps/website/screens/components/contextual-menu/code/ContextualMenuCodePage.tsx
- apps/website/screens/components/dialog/code/examples/withContent.ts
- apps/website/screens/components/flex/code/FlexCodePage.tsx
- apps/website/screens/components/paragraph/code/ParagraphCodePage.tsx
- apps/website/screens/components/quick-nav/code/QuickNavCodePage.tsx
- apps/website/screens/components/status-light/code/StatusLightCodePage.tsx
- apps/website/screens/components/tooltip/TooltipPageLayout.tsx
- apps/website/screens/components/tooltip/code/TooltipCodePage.tsx
- apps/website/screens/components/tooltip/code/examples/basicUsage.ts
- apps/website/screens/components/tooltip/specs/TooltipSpecsPage.tsx
- apps/website/screens/components/tooltip/usage/TooltipUsagePage.tsx
- apps/website/screens/overview/releases/ReleasesPage.tsx
- apps/website/screens/principles/themes/ThemesPage.tsx
- apps/website/screens/theme-generator/ThemeGenerator.tsx
- apps/website/screens/theme-generator/components/previews/Dialog.tsx
- apps/website/screens/utilities/halstack-provider/HalstackProviderPage.tsx
- package.json
- packages/cloudscape-themed/src/index.ts
- packages/lib/package.json
**Checklist**
**Purpose**
Some things I saw after launching the new repo structure and the 13th version of Halstack
Minor updates (formatting, .md files, etc)
> Some updates after merging Turborepo

- apps/website/screens/common/sidenav/SidenavLogo.tsx
- scripts/release-website.js
**Checklist**
The version of the halstack site is not properly visible. This is due to some issues with the publish release workflow. This PR tries to solve this.
> Changes to the release website workflow

- .github/workflows/publish-next.yml
- .github/workflows/publish-website.yml
**Checklist**
Updated workflow to try to fix next badge error.
> Publish website workflow updates

- apps/website/screens/principles/typography/code/TypographyCodePage.tsx
> Small change to force publish-website workflow

- .github/workflows/publish-next.yml
- .github/workflows/publish-website.yml
**Checklist**
There was a bug in publish-website and publish-next not getting ENV variables.
> Fix `publish-website` and `publish-next` workflows

- apps/website/screens/principles/typography/code/TypographyCodePage.tsx
Reverts dxc-technology/halstack-react#2050
> Revert "Small change to force publish-website workflow"

- apps/website/screens/principles/typography/code/TypographyCodePage.tsx
Reverts dxc-technology/halstack-react#2053
> Revert "Small change to force publish-website workflow""

- apps/website/next.config.js
- scripts/release-website.js
> Added fix for displayed version in website

- apps/website/screens/components/data-grid/DatagridPageLayout.tsx
**Checklist**
**Purpose**
This might fix the issues we are having with the data grid styles in website
> Possible fix to datagrid styles in website

- apps/website/global-styles.css
- apps/website/screens/components/data-grid/DatagridPageLayout.tsx
> Trying a different fix for datagrid Styles

- apps/website/global-styles.css
- apps/website/pages/_app.tsx
- apps/website/public/styles.css
> Adding data grid styles as a stylesheet

- packages/lib/src/data-grid/DataGrid.tsx
**Checklist**
**Purpose**
Added check before calling onGridRowsChange
> added check before calling function

- packages/lib/jest.config.js
**Checklist**
**Purpose**
Added coverage data to tests.
> Add coverage to the tests

- apps/website/next-env.d.ts
- package-lock.json
- packages/lib/package.json
- packages/lib/tsup.config.ts
**Checklist**
**Purpose**
Improve the bundle size and optimise the library's build process—more understandable build commands.
New tsup configuration file to extract build options into a file: `tsup.config.ts`. New flags where added to improve the bundle size and the generated files exported code.
> Tsup build updates

- packages/lib/src/resultset-table/ResultsetTable.tsx
**Checklist**
There was a specific scenario where the page was not updating after having the rowCount to zero due to filtering.
> Added fix to cover filtering issue with paginator

- apps/website/screens/components/data-grid/code/DataGridCodePage.tsx
- apps/website/screens/components/data-grid/code/examples/actionsCell.ts
- apps/website/screens/components/data-grid/specs/DataGridSpecsPage.tsx
- apps/website/screens/components/resultset-table/code/ResultsetTableCodePage.tsx
- apps/website/screens/components/table/code/TableCodePage.tsx
- apps/website/screens/theme-generator/components/previews/DataGrid.tsx
- packages/lib/src/HalstackContext.tsx
- packages/lib/src/chip/Chip.tsx
- packages/lib/src/common/variables.ts
- packages/lib/src/data-grid/DataGrid.stories.tsx
- packages/lib/src/data-grid/DataGrid.tsx
- packages/lib/src/data-grid/utils.tsx
- packages/lib/src/header/Header.tsx
- packages/lib/src/resultset-table/ResultsetTable.stories.tsx
- packages/lib/src/table/Table.stories.tsx
- packages/lib/src/table/types.ts
**Checklist**
**Purpose**
Actions cell compound component added to the data grid.
> Actions cell added to the dataGrid

- packages/lib/src/file-input/FileItem.tsx
**Checklist**
Additional check added in case it is undefined.
> Exception fix in File Item

- packages/lib/package.json
**Checklist**
**Purpose**
Test next versions in projects with a peerdependency set to 14.
> Added version 14.0.0 to package

- apps/website/screens/components/slider/code/SliderCodePage.tsx
- packages/lib/src/slider/Slider.test.tsx
- packages/lib/src/slider/Slider.tsx
- packages/lib/src/slider/types.ts
**Checklist**
**Purpose**
`ariaLabel` prop added to slider component
> ariaLabel prop added to slider component

- apps/website/screens/components/spinner/code/SpinnerCodePage.tsx
- packages/lib/src/spinner/Spinner.test.tsx
- packages/lib/src/spinner/Spinner.tsx
- packages/lib/src/spinner/types.ts
**Checklist**
`ariaLabel` prop added to the spinner component to improve accessibility when label is not available.
> ariaLabel prop added to spinner

- package-lock.json
**Checklist**
**Purpose**
We have a moderate vulnerability in the repo.
Update `nanoid` package version to fix the vulnerability.
> `nanoid` dependency vulnerability fixed

- packages/lib/src/styles/scroll.tsx
**Checklist**
Global styles for components with scroll: `styles/scroll.tsx`. This file creates a common mixin for every styled component with `overflow` set to `auto`.
> Create global scroll styles

- packages/lib/.storybook/preview.tsx
**Checklist**
**Purpose**
Some stories where having problems when executing their `preVisit` hook in the accessibility test due to `defaultViewport: "reset"` not being recommended anymore (as of the latest versions of storybook, this setting is the default behavior).
I was planning to add some improvements for viewport sizes using globals in this PR but they are part of storybook 9.0 and they are still in an alpha state, but they can be very interesting in the future, specially if we plan to add themes in storybook now that we are implementing our design tokens.
> Solved story context error

- package-lock.json
- packages/lib/src/link/Link.tsx
**Checklist**
There was a minor problem with spacing not matching the designs. Also updated package-lock due to a problem when building the project.
> Fixed link spacing

- apps/website/screens/components/chip/overview/examples/filter.ts
- apps/website/screens/components/paginator/overview/examples/flexibleConfiguration.ts
- apps/website/screens/components/paginator/overview/examples/scrollable.ts
- packages/lib/src/tabs/Tabs.tsx
> Fixed double closing tags in certain examples from documentation

- apps/website/pages/_app.tsx
**Checklist**
**Purpose**
fixes issues with FOUC.
> Adding safeguard to not render content before hydration

- packages/lib/src/resultset-table/ResultsetTable.stories.tsx
- packages/lib/src/resultset-table/ResultsetTable.tsx
**Checklist**
Added DxcFlex containers to match improvements in the latest release.
> Fixed alignment in resultset table header

- apps/website/next.config.js
- package-lock.json
- packages/lib/babel.config.js
- packages/lib/package.json
- packages/lib/tsup.config.ts
> Testing new fix for emotion problem

- apps/website/pages/_app.tsx
- apps/website/screens/components/data-grid/code/DataGridCodePage.tsx
**Checklist**
**Purpose**
The fix merged to fix FOUC messes with the initial redirection.
> FOUC fix reverted and dategrid doc layout improvement

- apps/website/screens/overview/installation/InstallationPage.tsx
**Checklist**
**Purpose**
Updated InstallationOverviewPage by replacing npm i react react-dom styled-components with npm i react react-dom react-data-grid @emotion/styled @emotion/react.
> Fix installation doc guidelines

- packages/lib/src/file-input/FileInput.test.tsx
- packages/lib/src/file-input/utils.ts
**Checklist**
**Purpose**
Changed how the preview is loadedto improve CSP compatibility
> Changed how the preview is loaded to improve CSP compatibility

- packages/lib/src/styles/variables.css
- packages/lib/src/toast/utils.ts
**Checklist**
**Purpose**
Reimplement toast to use semantic token and fix a token name
> Reimplement toast to use semantic token

- apps/website/screens/components/sidenav/code/SidenavCodePage.tsx
**Checklist**
**Purpose**
Removed duplicated 'title' prop on Sidenav Code Page
> Documentation fixes
