dxc-technology/halstack-react

.github/ISSUE_TEMPLATE/bug_report.md
.github/workflows/publish-next.yml
docs/src/common/Header.jsx
docs/src/pages/overview/Overview.jsx
lib/src/accordion/readme.md
lib/src/button/readme.md
lib/src/checkbox/readme.md
lib/src/progress-bar/readme.md
lib/src/radio/readme.md
lib/src/slider/readme.md
lib/src/spinner/readme.md
lib/src/switch/readme.md
lib/src/toggle/readme.md
lib/src/upload/readme.md

Removed all references to diaas, mostly links and library names in documentation files.
Also, for the `next` version generation on NPM, I am suggesting not naming it `0.0.0-XXX` by default, but instead, calculate what is the LATEST tag and use that as a prefix (e.g. current would be `0.0.1-XXX`). The proposed solution is based on [this solution](https://github.com/marketplace/actions/get-latest-tag) but I can't find a way of testing workflows without merging

☎️ removed all diaas references

---

lib/src/select/Select.jsx

Now when you focus on an option the label does not move.

[Patch] Select - avoid label displacement in focused option

---

app/src/pages/NewDate.jsx
docs/src/pages/components/cdk-components/new-date/api.jsx
docs/src/pages/components/cdk-components/new-date/examples/controlledDate.js
docs/src/pages/components/cdk-components/new-date/examples/uncontrolledDate.js
docs/src/pages/components/cdk-components/new-input-text/api.jsx
docs/src/pages/components/cdk-components/new-input-text/examples/invalidInput.js
docs/src/pages/components/cdk-components/number/api.jsx
docs/src/pages/components/cdk-components/password/api.jsx
lib/src/new-date/NewDate.jsx
lib/src/new-input-text/NewInputText.jsx
lib/test/NewDate.test.js

Summary:
- Added `clearable` prop for the new-date component. This involves new tests, docs updated and added examples in app.
- Compared and unified number, password, new-input, new-date and new-textarea documentations.
- Fixed an issue related to Error's icon container in the new inputs.

[Minor] Clearable for new-date, doc improvements & error icon container

---

app/src/pages/NewInputText.jsx
docs/src/pages/components/cdk-components/new-input-text/api.jsx
docs/src/pages/components/cdk-components/new-input-text/examples/actionInput.js
docs/src/pages/components/cdk-components/new-textarea/api.jsx
lib/src/new-input-text/NewInputText.jsx
lib/src/new-textarea/NewTextarea.jsx
lib/test/NewInputText.test.js
lib/test/NewTextarea.test.js

Summary of changes in the new-inputs and new-textarea:
- Action's icon can also be an URL (which becomes a `<img>` tag) apart from the usuals inline svg. Updated examples and documentation.
- New aria attributes included, related to errors: `aria-invalid`, `aria-describedby` and `aria-required`.
- Now errors aren't shown when an input is disabled.
- Added new error `"This field is required. Please, enter a value."` when it is not marked as optional (required) and the input is leaved without being filled. Tested and documented.

[Minor] Improvements to the NewInputs and NewTextarea

---

app/src/pages/Upload.jsx
docs/src/pages/components/cdk-components/file-input/FileInput.jsx
docs/src/pages/components/cdk-components/upload/Upload.jsx
docs/src/pages/components/cdk-components/upload/examples/upload.js
docs/src/pages/themeBuilder/components/previews/Upload.jsx
lib/src/main.js
lib/src/upload/Upload.jsx
lib/src/upload/readme.md
lib/test/Upload.test.js

- Renamed `DxcUpload` export to `V3DxcUpload`.
- Marked Upload as `Deprecated` using the chip and using a warning alert.
- Marked File Input as `Ready`.

[Major] Rename DxcUpload to V3DxcUpload.

---

lib/src/slider/Slider.jsx
lib/test/Slider.test.js

- Replaced `V3 Input Text` by `Text Input` in slider.
- Added check to only write numbers in slider's input.
- Changed text input size to `fillParent` and added `max-width` to its container.
- Changes in slider test.

[Patch] Text input in slider.

---

app/src/pages/InputText.jsx
docs/src/pages/components/cdk-components/dialog/examples/backgroundCloseDialog.js
docs/src/pages/components/cdk-components/input-text/examples/autocomplete.js
docs/src/pages/components/cdk-components/input-text/examples/controlledInputText.js
docs/src/pages/components/cdk-components/input-text/examples/darkThemedInputText.js
docs/src/pages/components/cdk-components/input-text/examples/fillParentInputInputText.js
docs/src/pages/components/cdk-components/input-text/examples/lebeledInputText.js
docs/src/pages/components/cdk-components/input-text/examples/maskedInputText.js
docs/src/pages/components/cdk-components/input-text/examples/sizedInputText.js
docs/src/pages/components/cdk-components/input-text/examples/uncontrolledInputText.js
docs/src/pages/themeBuilder/components/previews/Dialog.jsx
docs/src/pages/themeBuilder/components/previews/InputText.jsx
lib/src/date/Date.jsx
lib/src/input-text/InputText.jsx
lib/src/main.js
lib/test/InputText.test.js

Renamed `V3DxcInputText` to `DxcInputText`, as the new input text component is `DxcTextInput`, so the "V3" is not needed to differentiate.

[Minor] Rename V3DxcInputText to DxcInputText.

---

lib/src/resultsetTable/ResultsetTable.jsx

The paginator's select menu is hidden in the ResultsetTable.

[Patch] Paginator's select is hidden in table.

---

docs/src/pages/components/cdk-components/card/api.jsx
lib/src/card/Card.tsx

Closes #663 
This PR is also related to #618 
- Set outline color when focusing the card.
- Fix `outlined` prop that had wrong default value and did not work as expected.

[Patch] Card outlined prop fix and focus style

---

lib/src/alert/types.ts
lib/src/card/types.ts
lib/src/checkbox/types.ts
lib/src/header/types.ts
lib/src/radio/types.ts
lib/src/tabs/types.ts

Fix some `types.ts` files that didn't indicate the values of margins and paddings.

Fix type comments indicating margin values

---

docs/src/pages/components/cdk-components/button/api.jsx
lib/src/button/Button.tsx
lib/src/button/types.ts

Now `onClick` doesn't receive the `MouseEvent` event as a parameter.

[Major] Change Button's onClick parameters

---

lib/src/list/List.stories.tsx
lib/src/list/List.tsx
lib/src/row/Row.stories.tsx
lib/src/row/Row.tsx
lib/src/stack/Stack.stories.tsx
lib/src/stack/Stack.tsx

* Change `gutter` scale in `stack` and `row` components to allow bigger values 
* Add `xxxsmall` value to the scale
* Update list component default `gutter` in order to keep the same spacing value
Closes #749

[Major] Update gutter scale in row and stack components

---

lib/src/accordion/Accordion.stories.tsx
lib/src/accordion/Accordion.tsx
lib/src/card/Card.stories.tsx
lib/src/file-input/FileInput.stories.tsx
lib/src/heading/Heading.stories.tsx
lib/src/layout/ApplicationLayout.tsx
lib/src/link/Link.stories.tsx
lib/src/password-input/PasswordInput.stories.tsx
lib/src/resultsetTable/ResultsetTable.stories.tsx
lib/src/resultsetTable/ResultsetTable.tsx
lib/src/sidenav/Sidenav.stories.tsx
lib/src/spinner/Spinner.stories.jsx
lib/src/switch/Switch.stories.tsx
lib/src/table/Table.stories.jsx
lib/src/tabs/Tabs.stories.tsx
lib/src/tag/Tag.stories.tsx
lib/src/text-input/TextInput.stories.tsx
lib/src/textarea/Textarea.stories.jsx

- Fix dark test of the accordion.
- Added `expanded` prop to the `ExampleContainer` since some components were not seen in its entirety in the snapshots.
- Change some `smmall` titles to `small`.
- Added `< hr/>` in some stories in order to get the snapshot of the whole component with margin.
- Added `focus` to the arrow of the application layout.
- Added `focus` to the sortable heading in resultset table.
- Change in `Heading` `weight` tests.

Several fixes in stories

---

docs/src/pages/themeBuilder/themes/AdvancedTheme.json
docs/src/pages/themeBuilder/themes/schemas/Advanced.schema.json
lib/src/accordion/Accordion.tsx
lib/src/common/variables.js

Removed `background-color: transparent` in disabled accordion. Also removed unnecessary `disabledBackgroundColor` accordion's token.
Now in a disabled accordion group, the box shadow is only at the bottom:
Closes [781](https://github.com/dxc-technology/halstack-react/issues/781).

[Patch] Fix box shadow in disabled accordion group

---

lib/src/select/Select.tsx
lib/src/text-input/TextInput.tsx
lib/src/textarea/Textarea.tsx
lib/test/Select.test.js
lib/test/TextInput.test.js
lib/test/Textarea.test.js

Fixes #777. Summary (Select, Textarea and TextInput components):
- New aria attributes `aria-disabled` for disabled state.
- New aria attributes `aria-errormessage` and `aria-live` for error state.
- Tests for checking correct aria labelling.

Fix #777: New aria attributes for error and disabled states

---

lib/src/ThemeContext.tsx

The theme builder was not working well due to an issue with the ThemeProvider. This was been caused by a `useMemo` hook inside the exported component, whose array of dependencies was not working as expected, due to recent changes made to reimplement the component with typescript.
Apparently, the conditional array of dependencies was not working well with [conditional props](https://react-typescript-cheatsheet.netlify.app/docs/advanced/patterns_by_usecase#props-one-or-the-other-but-not-both) and the dynamic change of the theme, which is the main functionality of the theme-builder.
Solution: simplifying the types of ThemeProvider and destructuring its props to include both of them inside the array of dependencies.

Fix ThemeProvider memorized theme issue

---

lib/package.json

Currently `build:watch` does not work as expected. New file extensions are added to make it work.

Fix `build:watch` script

---

lib/src/text-input/TextInput.test.js

**Build and test** check from GitHub is _sometimes_ throwing an error in Text Input asynchronous tests.

Solve Text Input asynchronous tests issue in build 

---

lib/package.json
lib/src/date-input/DateInput.tsx

[Patch]Replacing Moment with Dayjs

---

website/screens/common/pagesList.ts

The footer of the site (`DocFooter.tsx`) had problems distinguishing paths starting with the same string, like: _"components/radio-group/"_ and _"components/radio/"_. This was due to the method `startsWith` which wasn't making match with the whole pathname.

Fix footer of the new site

---

website/screens/common/QuickNavContainer.tsx

Changed `max-width` to `width` of the quick nav content in order to avoid this:
Now it is working fine:

Fix width quickNavContainer in site

---

lib/src/select/Select.test.js
lib/src/select/Select.tsx

Fix `onBlur` event issue with required error

---

docs/src/pages/components/Components.jsx
docs/src/pages/components/cdk-components/applicationLayout/ApplicationLayout.jsx
docs/src/pages/components/cdk-components/header/Header.jsx
docs/src/pages/components/cdk-components/radio/Radio.jsx
lib/src/link/Link.tsx

- Fixed max width.
- Use of `React.Fragment` instead of a `div`.
- All Router Links changed in `docs` to be used correctly with DxcLink.

Link fixes

---

lib/src/inline/Inline.stories.tsx
lib/src/inline/Inline.tsx
lib/src/inline/types.ts

After some research, we find out that `justify-content` doesn't apply `stretch` and `baseline` values to the flexbox container and therefore there wasn't doing anything in the component at all.
See more in [MDN docs](https://developer.mozilla.org/es/docs/Web/CSS/justify-content) and [CSS-tricks flexbox guide](https://css-tricks.com/snippets/css/a-guide-to-flexbox/).

[Minor] Remove Inline `alignX` prop `stretch` and `baseline` values

---

website/screens/common/HeadingLink.tsx

When subtitles are too long, the website can not be seen correctly in small devices:
Added `word-break: break-word`  to be more readable:

Fixed too long subtitles

---

website/screens/common/example/Example.tsx

Added overflow to examples container to be able to scroll on them when the screen is small.

Fixed examples overflow

---

lib/src/quick-nav/QuickNav.tsx
website/screens/components/button/usage/examples/iconUsage.ts
website/screens/components/chip/code/examples/icons.ts
website/screens/components/dropdown/usage/examples/iconUsage.ts
website/screens/components/wizard/code/examples/icons.ts

Removed QuickNav component warnings:
1. `<li>` cannot be descendant of `<li>`
2. `key` warning
Removed `enable-background` warning of several svgs.

Removed several warnings

---

website/screens/common/example/Example.tsx
website/screens/components/application-layout/code/ApplicationLayoutCodePage.tsx

Now in the examples it is possible to hide the `Copy code` and `View code` actions. 
In the examples of the application layout they are hided.

Change actions visibility in site examples

---

lib/src/inline/Inline.stories.tsx
lib/src/inline/Inline.tsx
lib/src/inline/types.ts
website/screens/components/inline/code/InlineCodePage.tsx

As we discussed, a new prop `wrap` for the Inline component, so the user can decide whether items should be wrapped onto one line or jump to a new one we they can be fitted in a single row.

[Minor] New prop wrap for Inline component

---

lib/src/layout/ApplicationLayout.tsx

Sidenav tends to appear a fraction of a second when the new site is loaded in responsive mode since the beginning. A small code refactor to try to load the page with the sidenav collapsed since the first render and avoid its popping.

Fix Sidenav poping in responsive mode

---

lib/src/date-input/DateInput.tsx
lib/src/radio-group/RadioGroup.tsx
lib/src/tabs-nav/NavTabs.tsx
lib/src/tabs-nav/Tab.tsx
lib/src/text-input/TextInput.tsx

[Patch] Replace keycode for key in the affected components

---

.github/workflows/publish-next.yml
.github/workflows/publish-release.yml
scripts/release-website.js

- Change workflows and scripts to deploy the new website in `next` version and new releases. 
- Change S3 directory to `/halstack`.

New website deployment

---

website/screens/components/bleed/BleedPageLayout.tsx
website/screens/components/bulleted-list/BulletedListPageLayout.tsx
website/screens/components/flex/FlexPageLayout.tsx
website/screens/components/inset/InsetPageLayout.tsx
website/screens/components/nav-tabs/NavTabsPageLayout.tsx
website/screens/components/paragraph/ParagraphPageLayout.tsx
website/screens/components/quick-nav/QuickNavPageLayout.tsx
website/screens/components/radio-group/RadioGroupPageLayout.tsx
website/screens/components/typography/TypographyPageLayout.tsx

Changed status from `Experimental` to `Ready` in `Bleed`, `Bulleted List`, `Flex`, `Inset`, `Nav Tabs`, `Paragraph`, `Quick Nav`, `Radio Group` and `Typography` in website.

Change status to ready in several components

---

lib/src/checkbox/Checkbox.tsx

**Checklist**
**Closes #1320**

Fix disabled Checkbox focus appearance

---

lib/package.json

Before we had React 18.2.0 version, this forces the users to have this exact version as peer-dependency. Now, we allow the users to have any minor version that is part of React 18.

Working with any minor from React 18

---

lib/src/quick-nav/QuickNav.stories.tsx
lib/src/quick-nav/QuickNav.tsx

**Checklist**
Restructuring the DOM tree of the Quick Nav component, to match the HTML Standards and accessibility requirements.
Accessibility concerns related to the Quick Nav no longer appear.
**Closes #1316**

Refactoring the html code of the quick nav

---

lib/src/accordion-group/types.ts
lib/src/accordion/types.ts
lib/src/box/types.ts
lib/src/card/types.ts
lib/src/dialog/types.ts
lib/src/footer/types.ts
lib/src/header/types.ts
website/screens/components/accordion/code/AccordionCodePage.tsx
website/screens/components/box/code/BoxCodePage.tsx
website/screens/components/card/code/CardCodePage.tsx
website/screens/components/dialog/code/DialogCodePage.tsx
website/screens/components/footer/code/FooterCodePage.tsx
website/screens/components/header/code/HeaderCodePage.tsx

**Checklist**
**Purpose**
Update the documentation of affected components (accordion, box, card, dialog, footer & header) as having the prop padding deprecated. The positioning has been consulted with a designer previously.
Added alert to props sections of affected components.
Also, the deprecated tag has been added to the prop in the table.
**Closes #1297**

deprecating padding prop from accordion, box, card, dialog, footer & header

---

lib/src/dropdown/Dropdown.test.js
lib/src/dropdown/Dropdown.tsx
lib/src/number-input/NumberInput.test.js
lib/src/password-input/PasswordInput.test.js
lib/src/select/Select.tsx
lib/src/text-input/TextInput.test.js
lib/src/text-input/TextInput.tsx
lib/src/text-input/types.ts

**Checklist**
Now Radix Popover's presence depends on whether the text input is an autosuggest. This has been done with a conditional wrapper.
**Closes #1336**

Autosuggest update to avoid inconsistent roles with Radix

---

website/package.json
website/screens/common/HeadingLink.tsx
website/screens/common/Section.tsx
website/screens/components/quick-nav/QuickNavPageLayout.tsx
website/screens/components/quick-nav/code/QuickNavCodePage.tsx
website/screens/components/quick-nav/code/examples/withContent.ts
website/yarn.lock

**Checklist**
**Purpose**
Changed website to match changes from #1338. Waiting for this changes to be merged to change the version of halstack.
Added new prop `navSubtitle` for `Section` and `HeadingLink` components. We were using `title` for navigation and title of the section and subsection so it is not matching the new navigation made in the fix.
Now, to have unique navigation, subsections are composed by `section-title + subsection-title`.
**Closes #1338**

Changed website to match fix of quick nav

---

lib/src/radio-group/RadioGroup.test.js
lib/src/radio-group/RadioGroup.tsx
lib/src/select/Select.test.js
lib/src/select/Select.tsx

**Checklist**
Prevent the inner hidden inputs from these components from sending their value when the form that contains them is submitted. Also, new tests were added to prevent this from happening again.
**Closes #1342**

Fix Select and Radio Group from submitting its value when disabled

---

lib/src/table/Table.tsx

**Checklist**
**Purpose**
Padding from cells wasn't matching with the design guidelines.
Added padding 40px to right side of the last cell of the rows.
**Closes #1340**

Table fixed padding in last row item

---

lib/src/resultsetTable/ResultsetTable.tsx
lib/src/table/Table.tsx

**Checklist**
**Purpose**
Height rows in table and resultset table were not as in the design guidelines.
Resultset table was using a token which didn't exist so I removed it. Added `height: 60px` in the table for the rows. This fixed will be applied in both components.
**Closes #1339**

Table fixed height rows

---

lib/src/number-input/NumberInput.test.js
lib/src/password-input/PasswordInput.tsx
lib/src/text-input/TextInput.test.js
lib/src/text-input/TextInput.tsx
lib/src/text-input/types.ts

**Checklist**
As @GomezIvann said, adding `type="button"` in the actions solved the problem.
Added test.
**Closes #1363**

Fixed text input's action that executed form submit when clicked

---

lib/src/file-input/FileInput.test.js
lib/src/file-input/FileInput.tsx

**Checklist**
- Added `name` prop to hidden input, `disabled`, `aria-hidden` and `readOnly` as in the rest of the components that use hidden inputs.
- Updated style to `display: none` as in the rest of the components.
- Added test to check that the component is sending value when submitting with form.
**Closes #1351**

Fixed file input value when used on forms

---

lib/src/common/variables.js
lib/src/file-input/FileInput.stories.tsx
lib/src/file-input/FileInput.tsx
lib/src/file-input/FileItem.tsx
website/screens/principles/localization/LocalizationPage.tsx

**Checklist**
Summary:
- Change File Input's button size to `fitContent` in `file` mode.
- Updated stories of the File Input component to try to solve chromatic snapshot testing issues regarding each file item's delete button states.
- Minor code refactors and styling improvements.
- Include localization for Delete file action `aria-label` and `title`.
**Closes #1082 and #760**

File Input button size, stories update and small code refactors

---

lib/src/checkbox/Checkbox.stories.tsx
lib/src/checkbox/Checkbox.tsx

**Checklist**
To solve this issue, I just had to add `position: relative` to the checkbox parent container, so the `position: absolute` of the tick is calculated based on the actual positioning of the component as a whole. When an element is has position absolute, it is positioned relative to its closest positioned ancestor, if any; otherwise, it is placed relative to the initial [containing block](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block). 
**Closes #1355**

Fix Checkbox tick with sticky positioning

---

lib/src/date-input/DateInput.stories.tsx
website/package.json

**Checklist**
**Purpose**
Removed tab() from date input visual test in storybook and update website with the last version of halstack-react.
Removed tab() from date input visual test in storybook since it seems that works faster than material pulsate and it gives error.

Fix date input story and update website

---

lib/src/resultsetTable/Icons.tsx
lib/src/resultsetTable/ResultsetTable.stories.tsx
lib/src/resultsetTable/ResultsetTable.test.js
lib/src/resultsetTable/ResultsetTable.tsx
lib/src/resultsetTable/types.ts

**Checklist**
Some improvements to the Resultset Table:
- The Table now extends its width to the maximum available (100%), just like our regular Table, regardless of its container display.
- The gap between the sorting icons and a header title is now `8px`, as it stands in the documentation. Until now, that wasn't happening.
- Removing unnecessary styles from the component and useless containers, the component now is more simple.
- New visual tests.
- Minor code refactors and new accessibility features (`aria-sort` and `roles` were included).
Code:
```
<ExampleContainer>
<Title title="Flex" theme="light" level={4} />
<DxcFlex>
<DxcResultsetTable columns={columnsSortable} rows={rowsSortable} />
</DxcFlex> …
```

Some updates to Resultset table component

---

lib/src/slider/Slider.tsx
lib/src/spinner/Spinner.tsx
lib/src/switch/Switch.tsx
lib/src/tabs/Tabs.stories.tsx
lib/src/tabs/Tabs.tsx

**Checklist**
**Purpose**
Remove unnecessary z-index > 0 from components
For some components, the z-index set to >0 was unnecessary; in others, a stacking context is created to avoid any weird interaction with other components.
**Closes #1423 **

Removing unnecessary z-index or creating stacking contexts

---

lib/src/text-input/Suggestion.tsx
lib/src/text-input/TextInput.stories.tsx
lib/src/text-input/TextInput.test.js

**Checklist**
Special characters were transformed to regular expression so it was giving an error if they were invalid. 
Added `\` to escape the special characters. For example, if we write `*` in the input, internally the component will transform the value received to `\*` so it will be valid.
Added new test.
About the implementation, I have created a regular expression with the special characters that are giving error. Then I have converted it to string and created an array with each character. It is needed to remove the duplicate characters from the array because the function `.toString()` is literally converting the regular expression in a string without removing the characters `/`, `[` and `]` that are used to create de …

Fixed autosuggest input with special characters

---

lib/src/HalstackContext.tsx
lib/src/common/variables.js
lib/src/progress-bar/ProgressBar.stories.jsx
lib/src/progress-bar/ProgressBar.tsx
lib/src/wizard/Wizard.stories.tsx
website/screens/components/progress-bar/specs/ProgressBarSpecsPage.tsx
website/screens/principles/themes/ThemesPage.tsx
website/screens/theme-generator/themes/opinionated-theme.json
website/screens/theme-generator/themes/schemas/opinionated.schema.json

**Checklist**
**Purpose**
Review opinionated theme in the theme generator.
Added `overlayFontColor` theme input in progress bar opinionated theme.
Changed from `selectedFontColor` to `selectedStepFontColor` in wizard's opinionated theme.
`iconColor` theme input also affects `hoverIconColor` and `activeIconColor` in Chip component.

Changes opinionated theme

---

website/screens/components/nav-tabs/code/NavTabsCodePage.tsx

**Checklist**
**Purpose**
Updating broken links in nav tabs documentation regarding react router documentation.
The links are related to the examples that react-router provides (they moved the examples to a GitHub repository instead of hosting the examples in the documentation page) and the usage of the usehref hook.
**Closes #1452 **

Updating nav tabs broken links

---

lib/src/nav-tabs/Tab.tsx
website/package.json
website/screens/theme-generator/components/ComponentsPreviewMap.ts
website/screens/theme-generator/components/previews/NavTabs.tsx

**Checklist**
**Purpose**
Nav tabs previews are left in theme generator, so its opinionated theme cannot be changed.
Nav tabs previews added to theme generator.
**Closes #1502**

Added nav tabs previews to theme generator

---

lib/src/file-input/FileInput.tsx

**Checklist**
**Purpose**
Fix to be able to select same file after remove it.
Select a file, remove it and select the same file again. This is a limitation of the input file. Input file's value must be cleaned in order to be able to select it again.
Please refer to this [issue](https://github.com/ngokevin/react-file-reader-input/issues/11).
**Closes #1489**

Fix select a file after remove it in file input

---

website/screens/components/application-layout/code/ApplicationLayoutCodePage.tsx
website/screens/components/date-input/specs/DateInputSpecsPage.tsx
website/screens/components/dropdown/specs/DropdownSpecsPage.tsx
website/screens/components/flex/FlexPageLayout.tsx
website/screens/components/heading/usage/HeadingUsagePage.tsx
website/screens/components/link/code/LinkCodePage.tsx
website/screens/components/nav-tabs/code/NavTabsCodePage.tsx
website/screens/components/number-input/specs/NumberInputSpecsPage.tsx
website/screens/components/password-input/specs/PasswordInputSpecsPage.tsx
website/screens/components/resultset-table/usage/ResultsetTableUsagePage.tsx
website/screens/components/select/specs/SelectSpecsPage.tsx
website/screens/components/tabs/code/TabsCodePage.tsx
website/screens/components/tag/usage/TagUsagePage.tsx
website/screens/components/textarea/specs/TextareaSpecsPage.tsx
website/screens/components/toggle-group/specs/ToggleGroupSpecsPage.tsx
website/screens/principles/color/code/ColorCodePage.tsx
website/screens/principles/typography/usage/TypographyUsagePage.tsx
website/screens/utilities/halstack-provider/HalstackProviderPage.tsx

**Checklist**
**Purpose**
Fix broken links and fixes in documentation.

Fix broken links and fixes documentation

---

lib/src/HalstackContext.tsx
lib/src/accordion/Accordion.stories.tsx
lib/src/button/Button.stories.tsx
website/screens/principles/localization/examples/translations.ts

**Checklist**
The problem was the `JSON.parse(JSON.stringify(defaultTranslatedComponentLabels));` line at the method `parseLabels`. HalstackProvider `labels` object is not serializable (the object has functions inside), so the JSON methods won't work with this object, causing the error.
Also, the URL to an icon in both Accordion and Button stories was not founded anymore. Updated.
**Closes #1584**

Fixing Localization page error

---

lib/src/button/Button.tsx
lib/src/tabs/Tab.tsx
lib/src/tabs/Tabs.tsx
lib/src/textarea/Textarea.test.js
lib/src/textarea/Textarea.tsx
lib/src/utils/FocusLock.tsx

**Checklist**
As described in the linked issue, an error was spotted at the Dialog when using Jest and having to render this component. After some research, this problem was related to a [nwsapi](https://github.com/dperini/nwsapi) problem, which is a library used by Jest `jsdom`.
So, to fix this, the aria-disabled selector was removed from the tabbable elements query at the `FocusLock` component. Apart from solving this problem, the change is motivated by the fact that `aria-disabled` is a semantic attribute, i.e. it has no functionality on the component. Therefore, excluding elements with this attribute from the list of tabbable elements of the focus lock is unnecessary.
Issue: https://github.com/dperini/nwsapi/issues/81
**Closes #1586**

Fix Focus Lock issue

---

website/screens/common/QuickNavContainer.tsx

**Checklist**
**Purpose**
The column of the quick nav was still present when the media query made it disappear on small screens, making the rest of the content shrink too much.
Adding a media query which removes the quick nav grid column when the screen is smaller.

Fix responsive Quicknav in website

---

lib/src/alert/Alert.tsx
lib/src/chip/Chip.stories.tsx
lib/src/chip/Chip.tsx
lib/src/text-input/TextInput.tsx
website/screens/components/chip/code/ChipCodePage.tsx
website/screens/components/chip/code/examples/icons.ts
website/screens/components/chip/specs/ChipSpecsPage.tsx

**Checklist**
Summary:
- Fixes a spacing issue in the container of the Chip component.
- Some accessibility improvements to the component and small fixes to how interactive icons look.
- Code page updated with better explanations and examples.
**Closes #1608**

Chip spacing fix

---

lib/src/radio-group/Radio.tsx
lib/src/radio-group/RadioGroup.tsx
website/screens/components/radio-group/code/examples/uncontrolled.ts

**Checklist**
Code updates based on some issues spotted during UXPin integration.

Radio Group update

---

lib/src/paginator/Paginator.stories.tsx
lib/src/paginator/Paginator.test.js
lib/src/paginator/Paginator.tsx

**Checklist**
Paginator fails when `itemsPerPage` is `0` and `showGoToPage` is `true`, since it is making this operation `totalItems / itemsPerPage`. The result of this operation (`totalItems / 0`) is `Infinity`. So when it is trying to make `Array(Infinity)` it fails.
**Closes #1619**

Paginator fix when itemsPerPage is 0

---

lib/src/file-input/types.ts
website/screens/components/file-input/code/FileInputCodePage.tsx

**Checklist**
Deprecating the `name` prop of the File Input in both types and documentation.
**Closes #1637**

Deprecate `name` prop in File input

---

website/pages/_app.tsx
website/screens/common/DocFooter.tsx
website/screens/common/pagesList.ts
website/screens/overview/introduction/IntroductionPage.tsx

**Checklist**
Summary of the updates made to Halstack's main site:
1. New GitHub link was added at the bottom of the sidenav of the repository.
2. New icons added for the edit and report links at the `DocFooter` component.
3. New UXPin section in /the introduction page, replacing the older section referencing Adobe XD assets.

Improvements to Halstack documentation site

---

lib/src/BackgroundColorContext.tsx
lib/src/HalstackContext.tsx
lib/src/common/coreTokens.ts
lib/src/grid/Grid.stories.tsx
lib/src/grid/Grid.tsx

**Checklist**
**Purpose**
The result of the poll done by the team was to rename the `DxcGrid.GridItem` to just `DxcGrid.Item`.
Rename the `DxcGrid.GridItem` compound component to `DxcGrid.Item`. This change is applied at the library level.

Update GridItem naming in DxcGrid component

---

lib/src/button/Button.stories.tsx
lib/src/button/Button.test.js
lib/src/button/Button.tsx
lib/src/button/types.ts
website/screens/components/button/code/ButtonCodePage.tsx
website/screens/components/button/code/examples/basicUsage.ts
website/screens/components/button/code/examples/icons.ts
website/screens/components/button/specs/ButtonSpecsPage.tsx
website/screens/components/button/usage/ButtonUsagePage.tsx
website/screens/components/button/usage/examples/iconUsage.ts

**Checklist**
Added a new prop `title` to the Button component. It's meant to fulfil the requirement of an accessible icon-only button.
Also, some padding and margin specs from the component have been updated to make it more intuitive and consistent.
**Closes #1483**

Adding `title` prop to Button 

---

lib/package.json
scripts/build/copy-readme.js

**Checklist**
**Purpose**
Add the README.md of Halstack to the build of the library, so it appears on our npm [page](https://www.npmjs.com/package/@dxc-technology/halstack-react).
Added `copy-readme.js` file to the `/scripts` folder and execute it in the build process.

Include README file into the library build

---

lib/src/common/variables.ts
lib/src/date-input/DateInput.stories.tsx
lib/src/date-input/DateInput.test.js
lib/src/date-input/DateInput.tsx
lib/src/date-input/types.ts
lib/src/text-input/TextInput.stories.tsx
lib/src/text-input/TextInput.test.js
lib/src/text-input/TextInput.tsx
lib/src/text-input/types.ts
website/screens/components/date-input/code/DateInputCodePage.tsx
website/screens/components/text-input/code/TextInputCodePage.tsx
website/screens/components/text-input/specs/TextInputSpecsPage.tsx

**Checklist**
The new read-only variant of the Text Input and the Date Input.
**Closes #1687 and #1689**

Add `readOnly` prop to the Text Input and Date Input

---

lib/src/date-input/types.ts
lib/src/number-input/NumberInput.stories.tsx
lib/src/number-input/NumberInput.test.js
lib/src/number-input/NumberInput.tsx
lib/src/number-input/types.ts
lib/src/text-input/TextInput.stories.tsx
lib/src/text-input/TextInput.test.js
lib/src/text-input/TextInput.tsx
lib/src/text-input/types.ts
website/screens/components/number-input/code/NumberInputCodePage.tsx

**Checklist**
The new read-only variant of the Number Input.
**Closes #1697**

Add `readOnly` prop to Number Input component

---

website/screens/components/dropdown/usage/DropdownUsagePage.tsx

**Checklist**
The word "the" was duplicated in a sentence in the Dropdown's usage page.

Typo in Dropdown's Usage page

---

website/screens/components/spinner/specs/SpinnerSpecsPage.tsx

**Checklist**
**Purpose**
To change the value of the token assigned to spinner component.
In the Specs of the Spinner component, it is described that the font-weight of the percentage is 600, which is not correct, as it is 700. The token displayed for that font-weight is correct once we change that value, as font-bold sets font weight as bold (700).

Font-bold token was documented in the Spinner specs section

---

website/screens/components/progress-bar/specs/ProgressBarSpecsPage.tsx

**Checklist**
**Purpose**
Change the value of the label's font size in the specs section of the Progressbar component.
The font size in our Progressbar component label was described as 14px, with its consequent token being font-scale-02. However, both in implementation and in our design kit, this value is 12px, with its token being font-scale-03. I'm proposing both changes so that our specs are aligned with what we have in the rest of our resources.

Incorrect value for font size our Progressbar label

---

lib/src/file-input/FileInput.test.js
lib/src/file-input/FileInput.tsx
lib/src/file-input/types.ts

**Checklist**
This fixes the problem where, if we select the same file multiple times, it would stack instead of detecting it already was added. The testing was also updated in order to take this previously unrecorded scenario into account.
Differentiating between two files with the same name using the File API can be challenging because the API itself does not provide a unique identifier or file-specific information that distinguishes files solely based on their names. So I did a comparation of multiple parameters (name, size, lastModified...) in order to ensure that 2 files are equals.
**Closes #1736**

Updates FileInput component logic to prevent duplicates

---

website/screens/components/resultset-table/ResultsetTablePageLayout.tsx
website/screens/components/table/TablePageLayout.tsx

**Checklist**
The word **_analyze_** was incorrectly written as **_analazy_**.

Fixed typo in Table / Resultset table documentation

---

lib/src/select/Select.test.js
lib/src/select/Select.tsx

**Checklist**
The Select now doesn't crush with an empty array of options and the flag `searchable` to `true`.
**Closes #1786**

Fixed Assure Answers Select bug

---

lib/src/slider/Slider.tsx

**Checklist**
Minor update to the Slider component to fix some issues with SSR in NextJS.

Slider update

---

lib/src/common/variables.ts
lib/src/nav-tabs/NavTabs.tsx
lib/src/nav-tabs/Tab.tsx
website/screens/common/TabsPageLayout.tsx

**Checklist**
It has been decided that it is more appropiate for NavTabs component to always fill all the available space, that prevents ourselves from using "tricks" in order to achieve that.
**Closes #1525**

Added 100% width underline to NavTab

---

app/src/pages/Select.jsx
lib/package-lock.json
lib/src/select/Option.tsx
lib/src/select/Select.tsx
lib/src/text-input/TextInput.test.js

**Checklist**
A tooltip has been added to the Select component. When the label of an option, both when it is selected and in the listbox, is too long, a built-in tooltip will appear to help the user see the full text.
This functionality should be tested manually since there's no way of testing refs and document object calls with React Testing Library or snapshot testing (chromatic).
**Closes #1495**

Tooltip support in the Select component

---

website/screens/components/quick-nav/code/QuickNavCodePage.tsx

**Checklist**
Quicknav links level limit is now documented in Quicknav documentation.
**Closes #1810**

Added links level limit in Quicknav documentation.

---

lib/src/badge/Badge.tsx

**Checklist**
**Purpose**
When the badge is used in a small dynamic space like the columns of a table the badge wraps the text. 

Avoid text wrapping in the badge

---

lib/src/table/ActionsCell.tsx
website/package-lock.json
website/screens/common/TableCode.tsx
website/screens/components/resultset-table/code/ResultsetTableCodePage.tsx
website/screens/components/resultset-table/code/examples/reduced.ts
website/screens/components/table/code/TableCodePage.tsx
website/screens/components/table/code/examples/Icons.tsx
website/screens/components/table/code/examples/actions.ts

**Checklist**
Documentation related to the actions cell's API added to the table and resultset table code page.

New API documentation for ActionsCell

---

lib/src/accordion/Accordion.tsx
lib/src/common/variables.ts
website/screens/common/themes/advanced-theme.json
website/screens/theme-generator/themes/schemas/advanced.schema.json

**Checklist**
Fix typo in a token from the Accordion component. Replace `iconMarginRigth` with `iconMarginRight`.
**Closes #1763**

Fix typo in Accordion token

---

app/src/pages/Textarea.jsx
lib/src/textarea/Textarea.tsx

**Checklist**
Fixed auto-resizing issues when `verticalGrow` was set to `auto` and the value was changed programmatically in the controlled variant.
**Closes #1951**

Fixing Textarea `verticalGrow` as `auto`

---

lib/.storybook/preview.tsx
lib/src/HalstackContext.tsx
lib/src/common/fonts.css
lib/src/icon/Icon.tsx
lib/src/main.ts

**Checklist**
**Purpose**
The fonts css approach did not work in nextjs apps, so we decided in a temporal workaround.
This new approach was tested in app, website, storybook and an empty app with vite.

fonts css reverted back and changed the approach to load fonts

---

lib/src/number-input/NumberInput.stories.tsx
lib/src/number-input/NumberInput.tsx
lib/src/password-input/PasswordInput.stories.tsx
lib/src/password-input/PasswordInput.tsx
lib/src/select/Select.stories.tsx
lib/src/select/Select.tsx
lib/src/text-input/TextInput.stories.tsx
lib/src/text-input/TextInput.tsx

**Checklist**
**Purpose**
This PR fixes some strange behavior in the size of some of our input components.
Instead of components with 100% width being pushed by other components with a fixed width it was the other way around.
The password and number were not behaving correctly inside a flex component when the size was set to `fillParent`.
**Closes #1970**

Fixed some weird size behaviors in some input components

---

lib/src/file-input/FileItem.tsx

**Checklist**
File input's delete icon was not centered. Added `justify-content: center` to the button.
Before:
Now:
**Closes #1994**

Fix file input delete styles

---

lib/src/HalstackContext.tsx

**Checklist**
**Purpose**
A new warning appeared with this change and it seems that it was causing issues in some apps with font styles.

Reverted back Open sans import due to issues with globalStyles

---

website/screens/components/nav-tabs/code/NavTabsCodePage.tsx
website/screens/components/nav-tabs/code/examples/icons.ts
website/screens/components/tabs/code/TabsCodePage.tsx
website/screens/components/tabs/code/examples/icons.ts

**Checklist**
Added nav tabs icons and notifications example and added tabs notifications to the icons example.

Update tabs and nav tabs examples with icons and notifications

---

lib/src/dropdown/Dropdown.tsx
lib/src/select/Listbox.tsx
lib/src/select/Option.tsx
lib/src/select/Select.stories.tsx
lib/src/select/Select.tsx
lib/src/select/selectUtils.ts
lib/src/text-input/TextInput.tsx
lib/src/utils/useWidth.tsx
lib/test/accessibility/rules/specific/select/disabledRules.js

**Checklist**
Summary of changes:
- Fixed the Checkbox issue.
- Code updates and some refactors.
**Closes #2008**

Select updates

---

.github/workflows/chromatic.yml
packages/lib/src/HalstackContext.tsx
packages/lib/src/table/Table.tsx
packages/lib/src/table/types.ts

**Checklist**
Small update to check the new workflows and restored chromatic.

Checking workflows

---

.github/workflows/publish-next.yml
apps/website/screens/common/componentsList.json
apps/website/screens/components/tooltip/code/TooltipCodePage.tsx
apps/website/screens/components/tooltip/code/examples/basicUsage.ts

**Checklist**
Added missing example for tooltip and changed component status from experimental to new.
**Related to  #1964**

Added tooltip example to docs

---

apps/website/screens/principles/themes/ThemesPage.tsx
packages/lib/src/HalstackContext.tsx

**Checklist**
**Purpose**
Added opinionated theme support to the actionIcon in the table.
Closes #2047

Opinionated theme support added to the actionIcon in the table

---

.github/workflows/publish-next.yml
.github/workflows/publish-website.yml
apps/website/next.config.js
apps/website/screens/common/sidenav/SidenavLogo.tsx
scripts/release-website.js
turbo.json

Testing NEXT_PUBLIC env variables for turborepo + NextJS

---

apps/website/next.config.js
packages/lib/.storybook/test-runner.ts
packages/lib/src/table/Table.accessibility.test.tsx
packages/lib/src/table/Table.test.tsx
packages/lib/src/tooltip/Tooltip.accessibility.test.tsx
packages/lib/src/tooltip/Tooltip.test.tsx
scripts/release-website.js

**Checklist**
Fixes routing for release 13.2

Fix release env variables

---

apps/website/next.config.js
apps/website/screens/principles/typography/code/TypographyCodePage.tsx
scripts/release-website.js

**Checklist**
Latest fix for next version routing

Fix next version

---

apps/website/screens/components/box/specs/BoxSpecsPage.tsx
apps/website/screens/components/button/specs/ButtonSpecsPage.tsx
apps/website/screens/components/card/specs/CardSpecsPage.tsx
apps/website/screens/components/chip/specs/ChipSpecsPage.tsx
apps/website/screens/components/dialog/specs/DialogSpecsPage.tsx
apps/website/screens/components/dropdown/specs/DropdownSpecsPage.tsx
apps/website/screens/components/progress-bar/specs/ProgressBarSpecsPage.tsx
apps/website/screens/components/slider/specs/SliderSpecsPage.tsx
apps/website/screens/components/switch/specs/SwitchSpecsPage.tsx
apps/website/screens/components/toggle-group/specs/ToggleGroupSpecsPage.tsx
apps/website/screens/components/typography/specs/TypographySpecsPage.tsx

**Checklist**
As spotted in #2042, the units for spacing are not added when the value is 0. That would be appropiate to achieve a better consistency within the components' documentation.

Changed `0` for `0rem / 0px` to achieve better consistency in docs

---

packages/lib/src/action-icon/ActionIcon.stories.tsx
packages/lib/src/badge/Badge.stories.tsx
packages/lib/src/button/Button.stories.tsx
packages/lib/src/date-input/DateInput.stories.tsx
packages/lib/src/footer/Footer.stories.tsx
packages/lib/src/header/Header.stories.tsx
packages/lib/src/layout/ApplicationLayout.stories.tsx
packages/lib/src/select/Select.stories.tsx
packages/lib/src/tooltip/Tooltip.stories.tsx
packages/lib/src/tooltip/Tooltip.tsx
packages/lib/src/tooltip/TooltipContext.tsx

**Checklist**
Stories added to the following components (the ones that internally use `DxcTooltip` in any of their parts:
- ActionIcon
- Badge
- Button
- DateInput
- Footer
- Header
- ApplicationLayout
- Select
I have also a mechanism to protect against having multiple nested Tooltips overlapping, so I am covering this scenario in the tests and have added some logic to `DxcTooltip` component (only allowing the highest level tooltip to be displayed).
**Closes #2044**

Added tooltip visual tests to components that internally use them

---

packages/lib/src/HalstackContext.tsx

**Checklist**
**Purpose**
This should fix the issue related to the icons not loading in the site.

Added material symbols to the import in HalstackProvider

---

packages/lib/src/resultset-table/ResultsetTable.stories.tsx
packages/lib/src/resultset-table/ResultsetTable.test.tsx
packages/lib/src/resultset-table/ResultsetTable.tsx

**Checklist**
SortValue must take displayValue instead if it is undefined. After changing the  structure adding the "cells" item, this is not working.

Fixed problem in ResultsetTable when sortValue is missing

---

apps/website/screens/components/data-grid/DatagridPageLayout.tsx

**Checklist**
**Purpose**
Added a warning to the data grid documentation due to styling issues in NextJS apps.

Warning alert added to the data grid

---

packages/lib/.storybook/preview.tsx

**Checklist**
An unexpected behavior has been found. When inside the stories of a component that contains responsive behavior for small screens (for example iphonex), it doesn't matter if you go to a non-responsive story. The viewport mode that was triggered will remain. 
https://github.com/storybookjs/storybook/issues/27073#issue-2287234733

Fixed viewport not being reset after exiting responsive story

---

apps/website/screens/components/dropdown/code/DropdownCodePage.tsx
apps/website/screens/components/heading/usage/HeadingUsagePage.tsx
apps/website/screens/principles/themes/ThemesPage.tsx
packages/lib/src/HalstackContext.tsx
packages/lib/src/action-icon/ActionIcon.tsx
packages/lib/src/badge/Badge.tsx
packages/lib/src/button/Button.tsx
packages/lib/src/contextual-menu/ContextualMenu.stories.tsx
packages/lib/src/contextual-menu/ItemAction.tsx
packages/lib/src/date-input/DatePicker.tsx
packages/lib/src/dropdown/Dropdown.stories.tsx
packages/lib/src/dropdown/Dropdown.tsx
packages/lib/src/dropdown/types.ts
packages/lib/src/file-input/FileItem.tsx
packages/lib/src/footer/Footer.tsx
packages/lib/src/header/Header.tsx
packages/lib/src/layout/ApplicationLayout.tsx
packages/lib/src/select/ListOption.tsx
packages/lib/src/select/Select.stories.tsx
packages/lib/src/select/Select.tsx
packages/lib/src/select/selectUtils.ts
packages/lib/src/tabs/Tab.tsx
packages/lib/src/toggle-group/ToggleGroup.tsx
packages/lib/src/tooltip/Tooltip.tsx
packages/lib/src/tooltip/TooltipContext.tsx
packages/lib/src/tooltip/types.tsx

**Checklist**
Summary:
- Added a tooltip to long options with ellipses in the `Contextual Menu`.
- A tooltip was added to the `Select` component. Now our tooltip appears in long option labels and long selected values
- Updated tooltip implementation in our internal components. Now our tooltip doesn't add an extra container inside of our components.The build
- Added new title prop to the `Dropdown` component.
- Added new storybook tests to check all this functionality.

Tooltip updates

---

apps/website/screens/components/flex/code/FlexCodePage.tsx
packages/lib/src/flex/Flex.tsx
packages/lib/src/flex/types.ts

**Checklist**
The implementation of the Tooltip has been updated to match the Grid counterpart. Now, the default value of the props is consistent with the flexbox container default values, and we only add a new one if the users give props a value.
Thanks to this, our props are more accurate to the formal definition of the CSS Flexbox and add the ones passed by the code users, as they would expect.

Flex updates

---

apps/website/screens/components/date-input/code/DateInputCodePage.tsx
packages/lib/src/date-input/DateInput.stories.tsx
packages/lib/src/date-input/types.ts

**Checklist**
**Purpose**
New valid size "small" added to the dateInput.

Added new valid size to the dateinput

---

apps/website/package.json
apps/website/screens/common/example/Example.tsx
apps/website/screens/common/example/liveEditorTheme.ts
apps/website/screens/components/bleed/code/BleedCodePage.tsx
apps/website/screens/components/flex/code/FlexCodePage.tsx
apps/website/screens/components/grid/code/GridCodePage.tsx
apps/website/screens/components/inset/code/InsetCodePage.tsx
package-lock.json
packages/lib/src/bleed/Bleed.tsx
packages/lib/src/bleed/types.ts
packages/lib/src/common/coreTokens.ts
packages/lib/src/flex/Flex.tsx
packages/lib/src/flex/types.ts
packages/lib/src/footer/Footer.tsx
packages/lib/src/grid/Grid.tsx
packages/lib/src/grid/types.ts
packages/lib/src/inset/Inset.tsx
packages/lib/src/inset/types.ts

**Checklist**
Update the spacing properties of Halstack layout components to synchronise their value with the [spacing core tokens](https://developer.dxc.com/halstack/next/principles/spacing/#core-spacing-tokens). Currently, they only contain a subset of values. We need to provide all of them so that our users can enjoy the full Halstack design experience.
This PR also solves the `react-live` editor issue.
**Closes #2104**

Update spacing properties in layout components

---

packages/lib/src/file-input/FileInput.stories.tsx
packages/lib/src/file-input/FileItem.tsx

**Checklist**
`FileItems` inside `FileInput` were not displaying their `fileName` in a correct way, as the `no-wrap` option for `white-space` does indeed collapse consecutive spaces into one. 
**Closes #2106**

Added fix for whitespaces not displaying in filename

---

apps/website/pages/overview/installation.tsx
apps/website/screens/common/CodeBlock.tsx
apps/website/screens/common/QuickNavContainer.tsx
apps/website/screens/common/example/Example.tsx
apps/website/screens/common/pagesList.ts
apps/website/screens/overview/installation/InstallationPage.tsx
apps/website/screens/overview/installation/examples/building.ts
apps/website/screens/overview/introduction/IntroductionPage.tsx
packages/lib/src/layout/ApplicationLayout.tsx
packages/lib/src/link/Link.stories.tsx
packages/lib/src/link/Link.tsx

**Checklist**
We wanted to improve our documentation site as part of this release's Halstack enhancements. The first idea is to add Installation guidelines to help users install the `halstack-react` npm package.
**Extra changes:**
- Link padding removed to avoid extra spacing between words when there's a link in between.
- Adjusted responsive breakpoints in the website. Now the side nav disappears at a small laptop size and the quick nav at a table size.
- New CodeBlock component in the site.
- Example site component has been updated using Halstack color palette (it used to have its own colors).

New Installation page

---

packages/lib/src/tabs/Tabs.tsx

**Checklist**
Under certain interactions, the underline for the active item would move down until not being shown at all.
It has been happening since `DxcTabs` API was refactorized to use compound component. A change in the dependency array to calculate the width and height was causing this problem.
**Closes #2110**

Fixed underline issue within `Tabs`

---

packages/lib/.storybook/preview.tsx
packages/lib/src/HalstackContext.tsx
packages/lib/src/fonts.css
packages/lib/src/icon/Icon.tsx
packages/lib/src/index.ts
packages/lib/src/select/Select.stories.tsx
packages/lib/tsup.config.ts

**Checklist**
Using the `injectStyles` flag of tsup, we can add CSS styles to the Halstack build. I took advantage of that to import the Material Icons into our build, so that our components can have them by default, without needing to use `HalstackProvider`. This is an improvement on the current approach.

Adding Material Icons as an `@import` to the build using `injectStyles`

---

.github/workflows/publish-next.yml
.github/workflows/publish-release.yml
packages/lib/tsup.config.ts

**Checklist**
Workflows changed to accept any version instead of always 0.0.0

workflows updated to match any version in package instead of 0.0.0

---

apps/website/screens/components/dialog/code/DialogCodePage.tsx
apps/website/screens/components/dialog/code/examples/backgroundClick.ts
apps/website/screens/theme-generator/ImportDialog.tsx
packages/lib/src/dialog/Dialog.accessibility.test.tsx
packages/lib/src/dialog/Dialog.stories.tsx
packages/lib/src/dialog/Dialog.test.tsx
packages/lib/src/dialog/Dialog.tsx
packages/lib/src/dialog/types.ts
packages/lib/src/utils/FocusLock.tsx

**Checklist**
**Purpose**
The focus was not following the tabbing sequence in Dialog and Alert components when there was a component with the new Tooltip. It was an issue with the Focus Lock internal component.
Summary of changes:
- Fixed the issue. The `MutationObserver` from the `FocusLock` component was executing itself each time the focus changed, due to a flag of the observer (`{ attributes: true }`). Now it is only executing when the tree inside the component changes, which is the expected behavior.
- Fixed some usual issues with the Focus Lock like the Date Input calendar focus return on close, added focus guards etc.
- New tests.
- Change Dialog's prop `isCloseVisible` to `closable`, to match the new Alert approach for this same property.

Updates on the FocusLock and Dialog

---

packages/lib/src/bulleted-list/BulletedList.test.tsx
packages/lib/src/button/Button.test.tsx
packages/lib/src/button/Button.tsx
packages/lib/src/container/Container.test.tsx
packages/lib/src/container/Container.tsx
packages/lib/src/grid/Grid.tsx
packages/lib/src/image/Image.test.tsx
packages/lib/src/paragraph/Paragraph.test.tsx
packages/lib/src/quick-nav/QuickNav.test.tsx

**Checklist**
Improving the coverage from `halstack-react` to over `85%`.

Improving the coverage

---

apps/website/screens/components/textarea/code/TextareaCodePage.tsx
packages/lib/src/textarea/Textarea.test.tsx
packages/lib/src/textarea/Textarea.tsx
packages/lib/src/textarea/types.ts

**Checklist**
**Purpose**
`ariaLabel` prop added to improve accessibility in the textArea component.

ariaLabel prop added to textarea

---

apps/website/screens/components/checkbox/code/CheckboxCodePage.tsx
packages/lib/src/checkbox/Checkbox.test.tsx
packages/lib/src/checkbox/Checkbox.tsx
packages/lib/src/checkbox/types.ts

**Checklist**
**Purpose**
`ariaLabel` prop added to checkbox to improve accessibility.

ariaLabel prop added to checkbox

---

apps/website/screens/components/select/code/SelectCodePage.tsx
packages/lib/src/select/Select.test.tsx
packages/lib/src/select/Select.tsx
packages/lib/src/select/types.ts

**Checklist**
**Purpose**
`ariaLabel` prop added to select component.

ariaLabel prop added to select component

---

apps/website/screens/components/switch/code/SwitchCodePage.tsx
packages/lib/src/switch/Switch.test.tsx
packages/lib/src/switch/Switch.tsx
packages/lib/src/switch/types.ts

**Checklist**
**Purpose**
`ariaLabel` prop added to switch to improve accessibility in cases there is no label.

ariaLabel prop added to switch component

---

apps/website/screens/components/progress-bar/code/ProgressBarCodePage.tsx
packages/lib/src/progress-bar/ProgressBar.test.tsx
packages/lib/src/progress-bar/ProgressBar.tsx
packages/lib/src/progress-bar/types.ts

**Checklist**
**Purpose**
`ariaLabel` prop added to the progressBar component.

ariaLabel prop added to progressBar component

---

apps/website/screens/components/radio-group/code/RadioGroupCodePage.tsx
packages/lib/src/radio-group/RadioGroup.test.tsx
packages/lib/src/radio-group/RadioGroup.tsx
packages/lib/src/radio-group/types.ts

**Checklist**
**Purpose**
`ariaLabel` prop added to the radioGroup component.

ariaLabel prop added to the radioGroup

---

apps/website/screens/common/example/Example.tsx
apps/website/screens/components/number-input/code/NumberInputCodePage.tsx
packages/lib/src/number-input/NumberInput.stories.tsx
packages/lib/src/number-input/NumberInput.test.tsx
packages/lib/src/number-input/NumberInput.tsx
packages/lib/src/number-input/types.ts
packages/lib/src/text-input/TextInput.tsx

**Checklist**
Adding new prop `showControls` to the Number input.
Also, fixed the issue with the Copy code action inside the Halstack site code examples.
**Closes #2170**

Number input new prop `showControls`

---

apps/website/screens/components/data-grid/code/DataGridCodePage.tsx
packages/lib/src/data-grid/DataGrid.stories.tsx
packages/lib/src/data-grid/DataGrid.tsx
packages/lib/src/data-grid/types.ts

**Checklist**
**Purpose**
Added new option to have expandable rows expanded by default
Updated the useEffect to update correctly and exposed a row key to allow rows to be expanded by default.

Added option to have rows expanded by default

---

apps/website/screens/components/data-grid/code/DataGridCodePage.tsx
packages/lib/src/data-grid/DataGrid.stories.tsx
packages/lib/src/data-grid/DataGrid.tsx
packages/lib/src/data-grid/types.ts

**Checklist**
**Purpose**
A prop was added to allow the component to render in a different page.

Added the option to render in a different page by default

---

apps/website/pages/components/quick-nav/code.tsx
apps/website/pages/components/quick-nav/index.tsx
apps/website/screens/components/quick-nav/QuickNavPageLayout.tsx
apps/website/screens/components/quick-nav/code/QuickNavCodePage.tsx
apps/website/screens/components/quick-nav/overview/QuickNavOverviewsPage.tsx
packages/lib/src/quick-nav/QuickNav.tsx

**Checklist**
**Purpose**
Correct styles applied to the height and the focus of the Link inside the quicknav component

Quicknav height + focus styles corrected

---

apps/website/screens/common/QuickNavContainer.tsx
apps/website/screens/components/checkbox/overview/examples/labelPosition.ts
apps/website/screens/components/checkbox/overview/examples/stacking.ts
apps/website/screens/components/switch/overview/examples/labelPosition.ts
apps/website/screens/components/switch/overview/examples/stacking.ts
apps/website/screens/components/toggle-group/code/examples/uncontrolled.ts
packages/lib/src/paginator/Paginator.tsx
packages/lib/src/styles/variables.css

**Checklist**
New design tokens added to Halstack:
- Core:   
- New: `--font-size-40: 40px;`.
- Alias:
- Changed `--spacing-gap-xl` value from the core `--dimensions-48` to `--dimensions-32`.
- New: `--spacing-gap-xxl: var(--dimensions-48);`.
- New: `--typography-heading-xxl: var(--font-size-40);`.
- New: `--typography-heading-light: var(--font-weight-light);`.
- New: `--typography-heading-regular: var(--font-weight-regular);`.
- New: `--typography-link-m: var(--font-size-14);`.
- New: `--typography-link-regular: var(--font-weight-regular);`.
This has affected several places and components (`Link` and `Paginator`).
[Figma](https://www.figma.com/design/OXYsuCbwWiFYYM5lNEBaJw/Halstack-DS-%C2%B7-Foundations?node-id=6305-39&p=f&m=dev)

New design tokens

---

apps/website/screens/components/file-input/overview/FileInputOverviewPage.tsx

**Checklist**
**Purpose**
Small format changes to match other form input components' documentation.

small changes to doc to improve consistency between form input documentation

---

apps/website/screens/components/tabs/code/TabsCodePage.tsx
apps/website/screens/components/tabs/code/examples-new/controlled.ts
apps/website/screens/components/tabs/code/examples-new/icons.ts
apps/website/screens/components/tabs/code/examples-new/uncontrolled.ts
packages/lib/src/tabs/Tab.tsx
packages/lib/src/tabs/Tabs.stories.tsx
packages/lib/src/tabs/Tabs.test.tsx
packages/lib/src/tabs/Tabs.tsx
packages/lib/src/tabs/types.ts

**Checklist**
**Purpose**
With this change tabs can be used without a label as it is documented.
**Description*
This is a major change due to a required prop `tabId` being added to the `DxcTabs.Tab` component. This prop allows the tabs component to identify each tab even if there is not a label present.

TabId prop added to identify each tab

---

packages/lib/src/tabs/Tab.tsx
packages/lib/src/tabs/Tabs.stories.tsx
packages/lib/src/tabs/Tabs.test.tsx
packages/lib/src/tabs/Tabs.tsx
packages/lib/src/tabs/types.ts
packages/lib/tsconfig.json

**Checklist**
**Purpose**
To avoid creating a breaking change for now we will default the `tabId` value to the label if this one is set.

`tabId` prop is no longer required

---

packages/lib/src/accordion/Accordion.stories.tsx

**Checklist**
Added a special story in the Accordion when the sublabel is larger than the label so that  we can confirm that the label position is fine.

Added accordion stories

---

apps/website/next.config.js
apps/website/package.json
apps/website/pages/_app.tsx
apps/website/pages/_document.tsx
apps/website/pages/utilities/createEmotionCache.tsx
package-lock.json

**Checklist**
**Purpose**
We are trying to fix the styling issues in next.

Emotion cache added

---

apps/website/pages/_app.tsx
apps/website/pages/_document.tsx
apps/website/pages/createEmotionCache.ts

Reverts dxc-technology/halstack-react#2252

Revert "Added fix for FOUC problem"

---

packages/lib/src/dialog/Dialog.stories.tsx
packages/lib/src/styles/variables.css

**Checklist**
Z-Index from Dialog was higher than the elements using Radix Popover, which was causing them to appear behind. 
There was a scenario where Select would not appear if used inside a Dialog.

Fix dialog z-index

---

apps/website/screens/components/tabs/code/TabsCodePage.tsx
packages/lib/src/tabs/types.ts

**Checklist**
Tab's `tabId` prop was showing as required while in the typing it was not. Now the documentation correctly explains that either `tabId` or `label` have to be set for the component to work and the typing is restricted so that at least one of both have to be set while using TS.

Fix tabs typing

---

packages/lib/src/radio-group/utils.tsx

**Checklist**
**Purpose**
The component was using “secondary color” token instead of the primary one, being inconsistent with the rest of the components.

Reimplement radio group to use primary color token

---

apps/website/screens/components/paginator/code/PaginatorCodePage.tsx
packages/lib/src/number-input/NumberInput.stories.tsx
packages/lib/src/paginator/Paginator.stories.tsx
packages/lib/src/paginator/Paginator.tsx

**Checklist**
We already support virtualization for `Select` but `Paginator` was not making use of it. I have defined a threshold in which arrays with size higher than 100, where the performance starts to become worse, it is appropiate to incorporate it, using a `virtualHeight` of 304px which is the `max-height` that we previously supported on the Select.
**Closes**
[OC-19102](https://jira.dxc.com/browse/OC-19102)

Added virtualization to Paginator Select
